// Code generated by elval-gen. DO NOT EDIT.
// Source: custom.go

package customtypes

import (
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	WithAliases_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.MinLen(3))
		v.AddRule(validator.Email())
		return v
	}()
)

func (v *WithAliases) Validate() error {
	var err *errs.ValidationError
	if err = WithAliases_EmailValidator.Validate((string)(v.Email)); err != nil {
		return err
	}
	return err
}
