// Code generated by clientgen. DO NOT EDIT.
// Source: 02 Files & Streams Demo v1.0.0

package filesstreamsdemo

import (
	"context"
	"net/http"
	"strings"
	"fmt"
	"io"
	"bytes"
	"encoding/json"
	nooaclient "github.com/arkannsk/nooa/client"
	filesstream "github.com/arkannsk/nooa/examples/models/02_files_stream"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// httpc is the internal HTTP client shared by all tag adapters.
type httpc struct {
	BaseURL    string
	HTTPClient HTTPClient
	Codec      map[string]nooaclient.Codec
}

func newHTTPC(baseURL string, hc any) *httpc {
	var httpClient HTTPClient
	switch v := hc.(type) {
	case nil:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		httpClient = &stdHTTPClient{Client: v}
	case HTTPClient:
		httpClient = v
	default:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	}
	return &httpc{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: httpClient,
	}
}
// V1 is the HTTP client for 02 Files & Streams Demo.
type V1 struct {
	base *httpc
}

// New creates a new V1 client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *V1 {
	return &V1{base: newHTTPC(baseURL, hc)}
}

// Upload with custom annotated types
// POST /custom
func (c *V1) POSTCustom(ctx context.Context, input *filesstream.CustomWithAnnotations) (*POSTCustomResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/custom"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &POSTCustomResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Upload with mixed request
// POST /mixed
func (c *V1) POSTMixed(ctx context.Context, input *filesstream.MixedRequest) (*POSTMixedResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/mixed"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &POSTMixedResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Upload with standard file types
// POST /standard
func (c *V1) POSTStandard(ctx context.Context, input *filesstream.StandardFileTypes) (*POSTStandardResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/standard"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &POSTStandardResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// POSTCustomResponse is the response for the POSTCustom operation.
type POSTCustomResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status201 *filesstream.CustomWithAnnotations
}

// StatusCreated returns the unmarshaled response body for status 201.
func (r *POSTCustomResponse) StatusCreated() (*filesstream.CustomWithAnnotations, error) {
	if r.status201 != nil {
		return r.status201, nil
	}
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status201 = new(filesstream.CustomWithAnnotations)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// POSTMixedResponse is the response for the POSTMixed operation.
type POSTMixedResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status201 *filesstream.MixedRequest
}

// StatusCreated returns the unmarshaled response body for status 201.
func (r *POSTMixedResponse) StatusCreated() (*filesstream.MixedRequest, error) {
	if r.status201 != nil {
		return r.status201, nil
	}
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status201 = new(filesstream.MixedRequest)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// POSTStandardResponse is the response for the POSTStandard operation.
type POSTStandardResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status201 *filesstream.StandardFileTypes
}

// StatusCreated returns the unmarshaled response body for status 201.
func (r *POSTStandardResponse) StatusCreated() (*filesstream.StandardFileTypes, error) {
	if r.status201 != nil {
		return r.status201, nil
	}
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status201 = new(filesstream.StandardFileTypes)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}
