// Code generated by clientgen. DO NOT EDIT.
// Source: 02 Files & Streams Demo v1.0.0

package filesstreamsdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"bytes"
	"encoding/json"
	"strings"
	"github.com/arkannsk/nooa/client"
	filesstream "github.com/arkannsk/nooa/examples/models/02_files_stream"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// Client is the generated HTTP client for 02 Files & Streams Demo.
type Client struct {
	BaseURL     string
	HTTPClient  HTTPClient
	Token       string
	TokenPrefix string

	// Codec maps Content-Type to client.Codec for response body decoding.
	// If nil, defaults to JSON decoding for all types.
	Codec map[string]client.Codec
}

// New creates a new Client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *Client {
	var client HTTPClient
	switch v := hc.(type) {
	case nil:
		client = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		client = &stdHTTPClient{Client: v}
	case HTTPClient:
		client = v
	default:
		client = &stdHTTPClient{Client: &http.Client{}}
	}
	return &Client{
		BaseURL:     strings.TrimRight(baseURL, "/"),
		HTTPClient:  client,
		TokenPrefix: "Bearer",
	}
}


// Upload with custom annotated types
// POST /custom


// POSTCustomRequest holds parameters for POSTCustom.
type POSTCustomRequest struct {
	// Body is the request body.
	Body filesstream.CustomWithAnnotations
}

// POSTCustomResponse holds the response for POSTCustom.
type POSTCustomResponse struct {
	*http.Response
	client *Client
	status201 *filesstream.CustomWithAnnotations
}

func (r *POSTCustomResponse) StatusCreated() (*filesstream.CustomWithAnnotations, error) {
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.status201 != nil {
		return r.status201, nil
	}
	r.status201 = new(filesstream.CustomWithAnnotations)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// POSTCustom — Upload with custom annotated types
func (c *Client) POSTCustom(ctx context.Context, input *POSTCustomRequest) (*POSTCustomResponse, error) {

	u := c.BaseURL + "/custom"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &POSTCustomResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Upload with mixed request
// POST /mixed


// POSTMixedRequest holds parameters for POSTMixed.
type POSTMixedRequest struct {
	// Body is the request body.
	Body filesstream.MixedRequest
}

// POSTMixedResponse holds the response for POSTMixed.
type POSTMixedResponse struct {
	*http.Response
	client *Client
	status201 *filesstream.MixedRequest
}

func (r *POSTMixedResponse) StatusCreated() (*filesstream.MixedRequest, error) {
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.status201 != nil {
		return r.status201, nil
	}
	r.status201 = new(filesstream.MixedRequest)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// POSTMixed — Upload with mixed request
func (c *Client) POSTMixed(ctx context.Context, input *POSTMixedRequest) (*POSTMixedResponse, error) {

	u := c.BaseURL + "/mixed"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &POSTMixedResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Upload with standard file types
// POST /standard


// POSTStandardRequest holds parameters for POSTStandard.
type POSTStandardRequest struct {
	// Body is the request body.
	Body filesstream.StandardFileTypes
}

// POSTStandardResponse holds the response for POSTStandard.
type POSTStandardResponse struct {
	*http.Response
	client *Client
	status201 *filesstream.StandardFileTypes
}

func (r *POSTStandardResponse) StatusCreated() (*filesstream.StandardFileTypes, error) {
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.status201 != nil {
		return r.status201, nil
	}
	r.status201 = new(filesstream.StandardFileTypes)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// POSTStandard — Upload with standard file types
func (c *Client) POSTStandard(ctx context.Context, input *POSTStandardRequest) (*POSTStandardResponse, error) {

	u := c.BaseURL + "/standard"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &POSTStandardResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



