// Code generated by clientgen. DO NOT EDIT.
// Source: 07 Rewrite Demo v1.0.0

package rewritedemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	nooaclient "github.com/arkannsk/nooa/client"
	rewrite "github.com/arkannsk/nooa/examples/models/07_rewrite"
)

// GeoClient groups the Geo operations.
type GeoClient interface {
	GETGeofeature(ctx context.Context, input *rewrite.CreateLocationRequest) (*GETGeofeatureResponse, error)
	GETGeopoint(ctx context.Context, input *rewrite.CreateLocationWithPoint) (*GETGeopointResponse, error)
}

// geoAdapter implements GeoClient.
type geoAdapter struct {
	httpc *httpc
}

// Get location with geojson Feature
// GET /geo-feature
func (t *geoAdapter) GETGeofeature(ctx context.Context, input *rewrite.CreateLocationRequest) (*GETGeofeatureResponse, error) {

	path := "/geo-feature"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETGeofeatureResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// Get location with orb Point
// GET /geo-point
func (t *geoAdapter) GETGeopoint(ctx context.Context, input *rewrite.CreateLocationWithPoint) (*GETGeopointResponse, error) {

	path := "/geo-point"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETGeopointResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// GETGeofeatureResponse is the response for the GETGeofeature operation.
type GETGeofeatureResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *rewrite.CreateLocationRequest
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETGeofeatureResponse) StatusOk() (*rewrite.CreateLocationRequest, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(rewrite.CreateLocationRequest)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETGeopointResponse is the response for the GETGeopoint operation.
type GETGeopointResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *rewrite.CreateLocationWithPoint
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETGeopointResponse) StatusOk() (*rewrite.CreateLocationWithPoint, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(rewrite.CreateLocationWithPoint)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
