// Code generated by clientgen. DO NOT EDIT.
// Source: 07 Rewrite Demo v1.0.0

package rewritedemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"sync"
	nooaclient "github.com/arkannsk/nooa/client"
	rewrite "github.com/arkannsk/nooa/examples/models/07_rewrite"
)

// GeoClient groups the Geo operations.
type GeoClient interface {
	GETGeofeature(ctx context.Context, input *rewrite.CreateLocationRequest) (*GETGeofeatureResponse, error)
	GETGeopoint(ctx context.Context, input *rewrite.CreateLocationWithPoint) (*GETGeopointResponse, error)
}

// geoAdapter implements GeoClient.
type geoAdapter struct {
	httpc *httpc
}

// Get location with geojson Feature
// GET /geo-feature
func (t *geoAdapter) GETGeofeature(ctx context.Context, input *rewrite.CreateLocationRequest) (*GETGeofeatureResponse, error) {

	path := "/geo-feature"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETGeofeatureResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// Get location with orb Point
// GET /geo-point
func (t *geoAdapter) GETGeopoint(ctx context.Context, input *rewrite.CreateLocationWithPoint) (*GETGeopointResponse, error) {

	path := "/geo-point"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETGeopointResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// GETGeofeatureResponse is the response for the GETGeofeature operation.
// Call Close() when done to release the response body.
type GETGeofeatureResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *rewrite.CreateLocationRequest
}

// Close releases the response body. Always call when done.
func (r *GETGeofeatureResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// If the body was cached (via StatusOk or a prior read), each call
// returns a reset reader so the body can be read multiple times.
func (r *GETGeofeatureResponse) Body() io.ReadCloser {
	if r.resp == nil {
		return nil
	}
	if seeker, ok := r.resp.Body.(io.Seeker); ok {
		seeker.Seek(0, io.SeekStart)
	}
	return r.resp.Body
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It streams directly from resp.Body without caching, so the body is consumed.
// Do not call StatusOk() or Body() after Stream() — the body will be exhausted.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *GETGeofeatureResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if r.resp == nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// (bytes.Reader wrapped as io.ReadCloser) so subsequent reads can reuse the data.
func (r *GETGeofeatureResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = nooaclient.NewCachedBodyReader(data)
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETGeofeatureResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETGeofeatureResponse) StatusOk() (*rewrite.CreateLocationRequest, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(rewrite.CreateLocationRequest)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETGeopointResponse is the response for the GETGeopoint operation.
// Call Close() when done to release the response body.
type GETGeopointResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *rewrite.CreateLocationWithPoint
}

// Close releases the response body. Always call when done.
func (r *GETGeopointResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// If the body was cached (via StatusOk or a prior read), each call
// returns a reset reader so the body can be read multiple times.
func (r *GETGeopointResponse) Body() io.ReadCloser {
	if r.resp == nil {
		return nil
	}
	if seeker, ok := r.resp.Body.(io.Seeker); ok {
		seeker.Seek(0, io.SeekStart)
	}
	return r.resp.Body
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It streams directly from resp.Body without caching, so the body is consumed.
// Do not call StatusOk() or Body() after Stream() — the body will be exhausted.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *GETGeopointResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if r.resp == nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// (bytes.Reader wrapped as io.ReadCloser) so subsequent reads can reuse the data.
func (r *GETGeopointResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = nooaclient.NewCachedBodyReader(data)
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETGeopointResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETGeopointResponse) StatusOk() (*rewrite.CreateLocationWithPoint, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(rewrite.CreateLocationWithPoint)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
