// Code generated by clientgen. DO NOT EDIT.
// Source: 07 Rewrite Demo v1.0.0

package rewritedemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	nooaclient "github.com/arkannsk/nooa/client"
	rewrite "github.com/arkannsk/nooa/examples/models/07_rewrite"
)

// RewriteClient groups the Rewrite operations.
type RewriteClient interface {
	GETRewriteref(ctx context.Context, input *rewrite.WithRewriteRef) (*GETRewriterefResponse, error)
	GETRewritetype(ctx context.Context, input *rewrite.WithRewriteType) (*GETRewritetypeResponse, error)
}

// rewriteAdapter implements RewriteClient.
type rewriteAdapter struct {
	httpc *httpc
}

// Get struct with rewritten references
// GET /rewrite-ref
func (t *rewriteAdapter) GETRewriteref(ctx context.Context, input *rewrite.WithRewriteRef) (*GETRewriterefResponse, error) {

	path := "/rewrite-ref"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETRewriterefResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// Get struct with rewritten types
// GET /rewrite-type
func (t *rewriteAdapter) GETRewritetype(ctx context.Context, input *rewrite.WithRewriteType) (*GETRewritetypeResponse, error) {

	path := "/rewrite-type"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETRewritetypeResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// GETRewriterefResponse is the response for the GETRewriteref operation.
type GETRewriterefResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *rewrite.WithRewriteRef
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETRewriterefResponse) StatusOk() (*rewrite.WithRewriteRef, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(rewrite.WithRewriteRef)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETRewritetypeResponse is the response for the GETRewritetype operation.
type GETRewritetypeResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *rewrite.WithRewriteType
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETRewritetypeResponse) StatusOk() (*rewrite.WithRewriteType, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(rewrite.WithRewriteType)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
