// Code generated by clientgen. DO NOT EDIT.
// Source: 07 Rewrite Demo v1.0.0

package rewritedemo

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"sync"
	nooaclient "github.com/arkannsk/nooa/client"
	rewrite "github.com/arkannsk/nooa/examples/models/07_rewrite"
)

// RewriteClient groups the Rewrite operations.
type RewriteClient interface {
	GETRewriteref(ctx context.Context, input *rewrite.WithRewriteRef) (*GETRewriterefResponse, error)
	GETRewritetype(ctx context.Context, input *rewrite.WithRewriteType) (*GETRewritetypeResponse, error)
}

// rewriteAdapter implements RewriteClient.
type rewriteAdapter struct {
	httpc *httpc
}

// Get struct with rewritten references
// GET /rewrite-ref
func (t *rewriteAdapter) GETRewriteref(ctx context.Context, input *rewrite.WithRewriteRef) (*GETRewriterefResponse, error) {

	path := "/rewrite-ref"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETRewriterefResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// Get struct with rewritten types
// GET /rewrite-type
func (t *rewriteAdapter) GETRewritetype(ctx context.Context, input *rewrite.WithRewriteType) (*GETRewritetypeResponse, error) {

	path := "/rewrite-type"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETRewritetypeResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// GETRewriterefResponse is the response for the GETRewriteref operation.
// Call Close() when done to release the response body.
type GETRewriterefResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *rewrite.WithRewriteRef
}

// Close releases the response body. Always call when done.
func (r *GETRewriterefResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETRewriterefResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETRewriterefResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETRewriterefResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETRewriterefResponse) StatusOk() (*rewrite.WithRewriteRef, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(rewrite.WithRewriteRef)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETRewritetypeResponse is the response for the GETRewritetype operation.
// Call Close() when done to release the response body.
type GETRewritetypeResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *rewrite.WithRewriteType
}

// Close releases the response body. Always call when done.
func (r *GETRewritetypeResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETRewritetypeResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETRewritetypeResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETRewritetypeResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETRewritetypeResponse) StatusOk() (*rewrite.WithRewriteType, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(rewrite.WithRewriteType)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
