// Code generated by elval-gen. DO NOT EDIT.
// Source: errors.go

package models

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *ValidationError) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Short summary of the problem"
		prop.Example = "Validation failed"

		schema.Properties["title"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Detailed explanation"
		prop.Example = "Field 'email' is required"

		schema.Properties["detail"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Description = "HTTP status code"
		prop.Example = 400

		schema.Properties["status"] = prop
	}

	return schema
}

func (v *ValidationError) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/elval-integration/models.ValidationError"
}

func (v *UnauthorizedError) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Short summary"
		prop.Example = "Unauthorized"

		schema.Properties["title"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Why authorization failed"
		prop.Example = "Missing or invalid API key"

		schema.Properties["detail"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Description = "HTTP status code"
		prop.Example = 401

		schema.Properties["status"] = prop
	}

	return schema
}

func (v *UnauthorizedError) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/elval-integration/models.UnauthorizedError"
}

func (v *ForbiddenError) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Short summary"
		prop.Example = "Forbidden"

		schema.Properties["title"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Why access was denied"
		prop.Example = "You do not have permission to perform this action"

		schema.Properties["detail"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Description = "HTTP status code"
		prop.Example = 403

		schema.Properties["status"] = prop
	}

	return schema
}

func (v *ForbiddenError) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/elval-integration/models.ForbiddenError"
}

func (v *NotFoundError) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Short summary"
		prop.Example = "Not found"

		schema.Properties["title"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "What was not found"
		prop.Example = "Resource with id 'usr_123' does not exist"

		schema.Properties["detail"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Description = "HTTP status code"
		prop.Example = 404

		schema.Properties["status"] = prop
	}

	return schema
}

func (v *NotFoundError) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/elval-integration/models.NotFoundError"
}

func (v *ConflictError) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Short summary"
		prop.Example = "Conflict"

		schema.Properties["title"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Description of the conflict"
		prop.Example = "A user with this email already exists"

		schema.Properties["detail"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Description = "HTTP status code"
		prop.Example = 409

		schema.Properties["status"] = prop
	}

	return schema
}

func (v *ConflictError) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/elval-integration/models.ConflictError"
}

func (v *RateLimitError) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Short summary"
		prop.Example = "Too many requests"

		schema.Properties["title"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Rate limit details"
		prop.Example = "You have exceeded the rate limit. Try again in 60 seconds."

		schema.Properties["detail"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Description = "HTTP status code"
		prop.Example = 429

		schema.Properties["status"] = prop
	}

	return schema
}

func (v *RateLimitError) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/elval-integration/models.RateLimitError"
}
