// Code generated by elval-gen. DO NOT EDIT.
// Source: models.go

package models

import (
	oa "github.com/arkannsk/elval/pkg/oa"
)

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 5),
		Required:   make([]string, 0, 5),
		Ref:        v.GlobalRef(),
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "id")
		prop.Pattern = `^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`
		prop.Format = "uuid"

		prop.Description = "Unique identifier for the user"
		prop.Example = "550e8400-e29b-41d4-a716-446655440000"

		schema.Properties["id"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")
		prop.MinLength = oa.Ptr[int64](3)
		prop.MaxLength = oa.Ptr[int64](50)

		prop.Description = "The user's full name"
		prop.Title = "Full Name"
		prop.Example = "John Doe"

		schema.Properties["name"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "email")
		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		prop.Format = "email"
		prop.Example = "john.doe@example.com"

		schema.Properties["email"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Minimum = oa.Ptr[float64](18)
		prop.Maximum = oa.Ptr[float64](120)

		prop.Description = "Age in years (optional)"

		schema.Properties["age"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "role")
		prop.Enum = []interface{}{"admin", "user", "moderator"}

		prop.Description = "User role in the system"

		schema.Properties["role"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/elval-integration/models.User"
}

func (v *CreateUserRequest) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")
		prop.MinLength = oa.Ptr[int64](3)

		prop.Example = "Mike Ivanov"

		schema.Properties["name"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "email")
		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		prop.Example = "m.ivanov@example.com"

		schema.Properties["email"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Example = "25"

		schema.Properties["age"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		prop.Example = "user"

		schema.Properties["role"] = prop
	}

	return schema
}

func (v *CreateUserRequest) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/elval-integration/models.CreateUserRequest"
}
