// Code generated by elval-gen. DO NOT EDIT.
// Source: models.go

package models

import (
	"context"
	"github.com/arkannsk/elval/pkg/validator"
)

var (
	User_IDValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("ID")
		v.AddRule(validator.Required[string]())
		return v
	}()

	User_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(3))
		v.AddRule(validator.MaxLen(50))
		return v
	}()

	User_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()

	User_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Min[int](18))
		v.AddRule(validator.Max[int](120))
		original := v
		v = validator.New[int]("Age")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	User_RoleValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Role")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Enum[string]("admin", "user", "moderator"))
		return v
	}()
)

func (v *User) Decorate(ctx context.Context) error {

	return nil
}

func (v *User) Validate() error {

	if err := User_IDValidator.Validate(v.ID); err != nil {
		return err
	}

	if err := User_NameValidator.Validate(v.Name); err != nil {
		return err
	}

	if err := User_EmailValidator.Validate(v.Email); err != nil {
		return err
	}

	// Указатель Age
	if v.Age != nil {
		val := *v.Age
		if err := User_AgeValidator.Validate(val); err != nil {
			return &validator.ValidationError{
				Field:   "Age",
				Rule:    "nested",
				Message: "поле Age: " + err.Error(),
			}
		}
	}

	if err := User_RoleValidator.Validate(v.Role); err != nil {
		return err
	}
	return nil
}

var (
	CreateUserRequest_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(3))
		return v
	}()

	CreateUserRequest_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()

	CreateUserRequest_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		original := v
		v = validator.New[int]("Age")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	CreateUserRequest_RoleValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Role")
		return v
	}()
)

func (v *CreateUserRequest) Decorate(ctx context.Context) error {

	return nil
}

func (v *CreateUserRequest) Validate() error {

	if err := CreateUserRequest_NameValidator.Validate(v.Name); err != nil {
		return err
	}

	if err := CreateUserRequest_EmailValidator.Validate(v.Email); err != nil {
		return err
	}

	// Указатель Age
	if v.Age != nil {
		val := *v.Age
		if err := CreateUserRequest_AgeValidator.Validate(val); err != nil {
			return &validator.ValidationError{
				Field:   "Age",
				Rule:    "nested",
				Message: "поле Age: " + err.Error(),
			}
		}
	}

	if err := CreateUserRequest_RoleValidator.Validate(v.Role); err != nil {
		return err
	}
	return nil
}
