// Code generated by clientgen. DO NOT EDIT.
// Source: 13 Mixed Features Demo v1.0.0

package mixedfeaturesdemo

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	mixed "github.com/arkannsk/nooa/examples/models/13_mixed"
)

// HTTPClient is the interface that wraps the Do method.
// It is compatible with *http.Client and useful for testing.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client is the generated HTTP client for 13 Mixed Features Demo.
type Client struct {
	BaseURL     string
	HTTPClient  HTTPClient
	Token       string
	TokenPrefix string
}

// New creates a new Client.
func New(baseURL string, hc HTTPClient) *Client {
	if hc == nil {
		hc = &http.Client{}
	}
	return &Client{
		BaseURL:     strings.TrimRight(baseURL, "/"),
		HTTPClient:  hc,
		TokenPrefix: "Bearer",
	}
}


// Get address
// GET /address


// GETAddressResponse holds the response for GETAddress.
type GETAddressResponse struct {
	// Status 200 — 13_mixed.Address
	Status200 mixed.Address
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETAddress — Get address
func (c *Client) GETAddress(ctx context.Context) (*GETAddressResponse, error) {

	u := c.BaseURL + "/address"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETAddressResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Get mega struct from HTTP parameters
// GET /mega


// GETMegaRequest holds parameters for GETMega.
type GETMegaRequest struct {
	// IncludeDeleted — IncludeDeleted parameter
	IncludeDeleted bool
	IncludeDeletedSet bool
	// APIVersion — APIVersion parameter
	APIVersion string
	APIVersionSet bool
}

// GETMegaResponse holds the response for GETMega.
type GETMegaResponse struct {
	// Status 200 — 13_mixed.MegaStruct
	Status200 mixed.MegaStruct
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETMega — Get mega struct from HTTP parameters
func (c *Client) GETMega(ctx context.Context, input *GETMegaRequest) (*GETMegaResponse, error) {

	u := c.BaseURL + "/mega"

	// Query parameters
	query := url.Values{}
	if input != nil && input.IncludeDeletedSet {
		query.Set("IncludeDeleted", fmt.Sprintf("%v", input.IncludeDeleted))
	}
	if len(query) > 0 {
		u += "?" + query.Encode()
	}

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if input != nil && input.APIVersionSet {
		httpReq.Header.Set("APIVersion", fmt.Sprintf("%v", input.APIVersion))
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETMegaResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Create mega struct
// POST /mega


// POSTMegaRequest holds parameters for POSTMega.
type POSTMegaRequest struct {
	// IncludeDeleted — IncludeDeleted parameter
	IncludeDeleted bool
	IncludeDeletedSet bool
	// APIVersion — APIVersion parameter
	APIVersion string
	APIVersionSet bool
}

// POSTMegaResponse holds the response for POSTMega.
type POSTMegaResponse struct {
	// Status 200 — 13_mixed.MegaStruct
	Status200 mixed.MegaStruct
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// POSTMega — Create mega struct
func (c *Client) POSTMega(ctx context.Context, input *POSTMegaRequest) (*POSTMegaResponse, error) {

	u := c.BaseURL + "/mega"

	// Query parameters
	query := url.Values{}
	if input != nil && input.IncludeDeletedSet {
		query.Set("IncludeDeleted", fmt.Sprintf("%v", input.IncludeDeleted))
	}
	if len(query) > 0 {
		u += "?" + query.Encode()
	}

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if input != nil && input.APIVersionSet {
		httpReq.Header.Set("APIVersion", fmt.Sprintf("%v", input.APIVersion))
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &POSTMegaResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Get admin variant
// GET /variant/admin


// GETVariantAdminResponse holds the response for GETVariantAdmin.
type GETVariantAdminResponse struct {
	// Status 200 — 13_mixed.AdminVariant
	Status200 mixed.AdminVariant
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETVariantAdmin — Get admin variant
func (c *Client) GETVariantAdmin(ctx context.Context) (*GETVariantAdminResponse, error) {

	u := c.BaseURL + "/variant/admin"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETVariantAdminResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Get user variant
// GET /variant/user


// GETVariantUserResponse holds the response for GETVariantUser.
type GETVariantUserResponse struct {
	// Status 200 — 13_mixed.UserVariant
	Status200 mixed.UserVariant
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETVariantUser — Get user variant
func (c *Client) GETVariantUser(ctx context.Context) (*GETVariantUserResponse, error) {

	u := c.BaseURL + "/variant/user"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETVariantUserResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



