// Code generated by clientgen. DO NOT EDIT.
// Source: 13 Mixed Features Demo v1.0.0

package mixedfeaturesdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"bytes"
	"encoding/json"
	nooaclient "github.com/arkannsk/nooa/client"
	mixed "github.com/arkannsk/nooa/examples/models/13_mixed"
)

// MixedClient groups the Mixed operations.
type MixedClient interface {
	POSTMega(ctx context.Context, input *mixed.MegaStruct) (*POSTMegaResponse, error)
	GETMega(ctx context.Context, input *mixed.MegaStruct) (*GETMegaResponse, error)
}

// mixedAdapter implements MixedClient.
type mixedAdapter struct {
	httpc *httpc
}

// Create mega struct
// POST /mega
func (t *mixedAdapter) POSTMega(ctx context.Context, input *mixed.MegaStruct) (*POSTMegaResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/mega"

	requestURL := t.httpc.BaseURL + path
	queryValues := url.Values{}
	if input.IncludeDeleted {
		queryValues.Add("includedeleted", fmt.Sprintf("%v", input.IncludeDeleted))
	}
	if len(queryValues) > 0 {
		requestURL += "?" + queryValues.Encode()
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("apiversion", fmt.Sprintf("%v", input.APIVersion))

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &POSTMegaResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// Get mega struct from HTTP parameters
// GET /mega
func (t *mixedAdapter) GETMega(ctx context.Context, input *mixed.MegaStruct) (*GETMegaResponse, error) {

	path := "/mega"

	requestURL := t.httpc.BaseURL + path
	queryValues := url.Values{}
	if input.IncludeDeleted {
		queryValues.Add("includedeleted", fmt.Sprintf("%v", input.IncludeDeleted))
	}
	if len(queryValues) > 0 {
		requestURL += "?" + queryValues.Encode()
	}

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("apiversion", fmt.Sprintf("%v", input.APIVersion))

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETMegaResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// POSTMegaResponse is the response for the POSTMega operation.
type POSTMegaResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *mixed.MegaStruct
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *POSTMegaResponse) StatusOk() (*mixed.MegaStruct, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(mixed.MegaStruct)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETMegaResponse is the response for the GETMega operation.
type GETMegaResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *mixed.MegaStruct
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETMegaResponse) StatusOk() (*mixed.MegaStruct, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(mixed.MegaStruct)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
