// Code generated by clientgen. DO NOT EDIT.
// Source: 13 Mixed Features Demo v1.0.0

package mixedfeaturesdemo

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"sync"
	nooaclient "github.com/arkannsk/nooa/client"
	mixed "github.com/arkannsk/nooa/examples/models/13_mixed"
)

// NestedClient groups the Nested operations.
type NestedClient interface {
	GETAddress(ctx context.Context, input *mixed.Address) (*GETAddressResponse, error)
}

// nestedAdapter implements NestedClient.
type nestedAdapter struct {
	httpc *httpc
}

// Get address
// GET /address
func (t *nestedAdapter) GETAddress(ctx context.Context, input *mixed.Address) (*GETAddressResponse, error) {

	path := "/address"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETAddressResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// GETAddressResponse is the response for the GETAddress operation.
// Call Close() when done to release the response body.
type GETAddressResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *mixed.Address
}

// Close releases the response body. Always call when done.
func (r *GETAddressResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETAddressResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETAddressResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETAddressResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETAddressResponse) StatusOk() (*mixed.Address, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(mixed.Address)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
