// Code generated by clientgen. DO NOT EDIT.
// Source: 13 Mixed Features Demo v1.0.0

package mixedfeaturesdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	nooaclient "github.com/arkannsk/nooa/client"
	mixed "github.com/arkannsk/nooa/examples/models/13_mixed"
)

// VariantsClient groups the Variants operations.
type VariantsClient interface {
	GETVariantAdmin(ctx context.Context, input *mixed.AdminVariant) (*GETVariantAdminResponse, error)
	GETVariantUser(ctx context.Context, input *mixed.UserVariant) (*GETVariantUserResponse, error)
}

// variantsAdapter implements VariantsClient.
type variantsAdapter struct {
	httpc *httpc
}

// Get admin variant
// GET /variant/admin
func (t *variantsAdapter) GETVariantAdmin(ctx context.Context, input *mixed.AdminVariant) (*GETVariantAdminResponse, error) {

	path := "/variant/admin"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETVariantAdminResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// Get user variant
// GET /variant/user
func (t *variantsAdapter) GETVariantUser(ctx context.Context, input *mixed.UserVariant) (*GETVariantUserResponse, error) {

	path := "/variant/user"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETVariantUserResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// GETVariantAdminResponse is the response for the GETVariantAdmin operation.
type GETVariantAdminResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *mixed.AdminVariant
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETVariantAdminResponse) StatusOk() (*mixed.AdminVariant, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(mixed.AdminVariant)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETVariantUserResponse is the response for the GETVariantUser operation.
type GETVariantUserResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *mixed.UserVariant
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETVariantUserResponse) StatusOk() (*mixed.UserVariant, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(mixed.UserVariant)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
