// Code generated by clientgen. DO NOT EDIT.
// Source: 13 Mixed Features Demo v1.0.0

package mixedfeaturesdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"sync"
	nooaclient "github.com/arkannsk/nooa/client"
	mixed "github.com/arkannsk/nooa/examples/models/13_mixed"
)

// VariantsClient groups the Variants operations.
type VariantsClient interface {
	GETVariantAdmin(ctx context.Context, input *mixed.AdminVariant) (*GETVariantAdminResponse, error)
	GETVariantUser(ctx context.Context, input *mixed.UserVariant) (*GETVariantUserResponse, error)
}

// variantsAdapter implements VariantsClient.
type variantsAdapter struct {
	httpc *httpc
}

// Get admin variant
// GET /variant/admin
func (t *variantsAdapter) GETVariantAdmin(ctx context.Context, input *mixed.AdminVariant) (*GETVariantAdminResponse, error) {

	path := "/variant/admin"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETVariantAdminResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// Get user variant
// GET /variant/user
func (t *variantsAdapter) GETVariantUser(ctx context.Context, input *mixed.UserVariant) (*GETVariantUserResponse, error) {

	path := "/variant/user"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETVariantUserResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// GETVariantAdminResponse is the response for the GETVariantAdmin operation.
// Call Close() when done to release the response body.
type GETVariantAdminResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *mixed.AdminVariant
}

// Close releases the response body. Always call when done.
func (r *GETVariantAdminResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// If the body was cached (via StatusOk or a prior read), each call
// returns a reset reader so the body can be read multiple times.
func (r *GETVariantAdminResponse) Body() io.ReadCloser {
	if r.resp == nil {
		return nil
	}
	if seeker, ok := r.resp.Body.(io.Seeker); ok {
		seeker.Seek(0, io.SeekStart)
	}
	return r.resp.Body
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It streams directly from resp.Body without caching, so the body is consumed.
// Do not call StatusOk() or Body() after Stream() — the body will be exhausted.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *GETVariantAdminResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if r.resp == nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// (bytes.Reader wrapped as io.ReadCloser) so subsequent reads can reuse the data.
func (r *GETVariantAdminResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = nooaclient.NewCachedBodyReader(data)
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETVariantAdminResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETVariantAdminResponse) StatusOk() (*mixed.AdminVariant, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(mixed.AdminVariant)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETVariantUserResponse is the response for the GETVariantUser operation.
// Call Close() when done to release the response body.
type GETVariantUserResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *mixed.UserVariant
}

// Close releases the response body. Always call when done.
func (r *GETVariantUserResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// If the body was cached (via StatusOk or a prior read), each call
// returns a reset reader so the body can be read multiple times.
func (r *GETVariantUserResponse) Body() io.ReadCloser {
	if r.resp == nil {
		return nil
	}
	if seeker, ok := r.resp.Body.(io.Seeker); ok {
		seeker.Seek(0, io.SeekStart)
	}
	return r.resp.Body
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It streams directly from resp.Body without caching, so the body is consumed.
// Do not call StatusOk() or Body() after Stream() — the body will be exhausted.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *GETVariantUserResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if r.resp == nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// (bytes.Reader wrapped as io.ReadCloser) so subsequent reads can reuse the data.
func (r *GETVariantUserResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = nooaclient.NewCachedBodyReader(data)
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETVariantUserResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETVariantUserResponse) StatusOk() (*mixed.UserVariant, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(mixed.UserVariant)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
