// Code generated by elval-gen. DO NOT EDIT.
// Source: generics.go

package generics

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *GenericStruct) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"

		prop.Description = "Optional name"

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "integer"

		prop.Description = "Optional age"

		schema.Properties["age"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"

		prop.Description = "Result of computation"

		schema.Properties["data"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}
		prop.Items.Ref = "#/components/schemas/github.com/arkannsk/nooa/examples/models/05_generics.Item"

		prop.Description = "Slice of optional items"

		schema.Properties["items"] = prop
	}

	return schema
}

func (v *GenericStruct) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/05_generics.GenericStruct"
}

func (v *Item) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["id"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["name"] = prop
	}

	return schema
}

func (v *Item) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/05_generics.Item"
}

func (v *WithCustomGeneric) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"

		prop.Description = "Custom generic field (rewritten as string)"

		schema.Properties["value"] = prop
	}

	return schema
}

func (v *WithCustomGeneric) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/05_generics.WithCustomGeneric"
}
