{{- /* client.go.tpl — main template for the HTTP client */ -}}
// Code generated by clientgen. DO NOT EDIT.
// Source: {{ .Title }} v{{ .Version }}

package {{ .Package }}

import (
	"context"
	"fmt"
	"io"
	"net/http"
{{- if .HasQueryParams }}
	"net/url"
{{- end }}
{{- if .HasRequestBody }}
	"bytes"
	"encoding/json"
{{- end }}
	"strings"
	"github.com/arkannsk/nooa/client"
{{- range .Imports }}
{{- $alias := index $.PackageAliases . }}
{{- if $alias }}
	{{ $alias }} {{ . | printf "%q" }}
{{- else }}
	{{ . | printf "%q" }}
{{- end }}
{{- end }}
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// Client is the generated HTTP client for {{ .Title }}.
type Client struct {
	BaseURL     string
	HTTPClient  HTTPClient
	Token       string
	TokenPrefix string

	// Codec maps Content-Type to client.Codec for response body decoding.
	// If nil, defaults to JSON decoding for all types.
	Codec map[string]client.Codec
}

// New creates a new Client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *Client {
	var client HTTPClient
	switch v := hc.(type) {
	case nil:
		client = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		client = &stdHTTPClient{Client: v}
	case HTTPClient:
		client = v
	default:
		client = &stdHTTPClient{Client: &http.Client{}}
	}
	return &Client{
		BaseURL:     strings.TrimRight(baseURL, "/"),
		HTTPClient:  client,
		TokenPrefix: "Bearer",
	}
}

{{ range .Operations }}
// {{ .Summary }}
// {{ .Method }} {{ .Path }}
{{ template "method.go.tpl" . }}

{{ end }}
