{{- /* client.go.tpl — main template for the HTTP client */ -}}
// Code generated by clientgen. DO NOT EDIT.
// Source: {{ .Title }} v{{ .Version }}

package {{ .Package }}

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
{{- if .HasQueryParams }}
	"net/url"
{{- end }}
	"strings"
{{- if .HasRequestBody }}
	"bytes"
{{- end }}
{{- range .Imports }}
{{- $alias := index $.PackageAliases . }}
{{- if $alias }}
	{{ $alias }} {{ . | printf "%q" }}
{{- else }}
	{{ . | printf "%q" }}
{{- end }}
{{- end }}
)

// HTTPClient is the interface that wraps the Do method.
// It is compatible with *http.Client and useful for testing.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client is the generated HTTP client for {{ .Title }}.
type Client struct {
	BaseURL     string
	HTTPClient  HTTPClient
	Token       string
	TokenPrefix string
}

// New creates a new Client.
func New(baseURL string, hc HTTPClient) *Client {
	if hc == nil {
		hc = &http.Client{}
	}
	return &Client{
		BaseURL:     strings.TrimRight(baseURL, "/"),
		HTTPClient:  hc,
		TokenPrefix: "Bearer",
	}
}

{{ range .Operations }}
// {{ .Summary }}
// {{ .Method }} {{ .Path }}
{{ template "method.go.tpl" . }}

{{ end }}
