{{- /* tag.go.tpl — template for a tag-specific interface and unexported adapter */ -}}
// Code generated by clientgen. DO NOT EDIT.
// Source: {{ .Title }} v{{ .Version }}

package {{ .Package }}

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"sync"
{{- if .HasPathParams }}
	"strings"
{{- end }}
{{- if .HasQueryParams }}
	"net/url"
{{- end }}
{{- if .HasRequestBody }}
	"bytes"
	"encoding/json"
{{- end }}
{{- if .NeedsClientPkg }}
	nooaclient "github.com/arkannsk/nooa/client"
{{- end }}
{{- range .Imports }}
{{- $alias := index $.PackageAliases . }}
{{- if $alias }}
	{{ $alias }} {{ . | printf "%q" }}
{{- else }}
	{{ . | printf "%q" }}
{{- end }}
{{- end }}
)

// {{ .InterfaceName }} groups the {{ .TagName }} operations.
type {{ .InterfaceName }} interface {
{{- range .Operations }}
	{{ .MethodName }}(ctx context.Context{{ if .HasModelInput }}, input *{{ .ModelInputGoType }}{{ else if .HasParams }}, input *{{ .MethodName }}Request{{ else }}, opts ...nooaclient.RequestOption{{ end }}) {{ if .HasResponse }}(*{{ .MethodName }}Response, error){{ else }}error{{ end }}
{{- end }}
}

// {{ .AdapterTypeName }} implements {{ .InterfaceName }}.
type {{ .AdapterTypeName }} struct {
	httpc *httpc
}

{{- $adapterTypeName := .AdapterTypeName }}
{{- range .Operations }}

// {{ .Summary }}
// {{ .Method }} {{ .Path }}
func (t *{{ $adapterTypeName }}) {{ .MethodName }}(ctx context.Context{{ if .HasModelInput }}, input *{{ .ModelInputGoType }}{{ else if .HasParams }}, input *{{ .MethodName }}Request{{ else }}, opts ...nooaclient.RequestOption{{ end }}) {{ if .HasResponse }}(*{{ .MethodName }}Response, error){{ else }}error{{ end }} {
{{- if .HasRequestBody }}
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return {{ retPrefix .HasResponse }}fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}
{{- end }}

	path := "{{ .Path }}"
{{- range .PathParams }}
	path = strings.ReplaceAll(path, "{{ "{" }}{{ .Name }}{{ "}" }}", fmt.Sprintf("%v", input.{{ .GoFieldName }}))
{{- end }}

	requestURL := t.httpc.BaseURL + path
{{- if .QueryParams }}
	queryValues := url.Values{}
{{- range .QueryParams }}
{{- if eq .GoType "string" }}
	if input.{{ .GoFieldName }} != "" {
		queryValues.Add("{{ .Name }}", input.{{ .GoFieldName }})
	}
{{- else if eq .GoType "bool" }}
	if input.{{ .GoFieldName }} {
		queryValues.Add("{{ .Name }}", fmt.Sprintf("%v", input.{{ .GoFieldName }}))
	}
{{- else }}
	if input.{{ .GoFieldName }} != 0 {
		queryValues.Add("{{ .Name }}", fmt.Sprintf("%v", input.{{ .GoFieldName }}))
	}
{{- end }}
{{- end }}
	if len(queryValues) > 0 {
		requestURL += "?" + queryValues.Encode()
	}
{{- end }}

	httpReq, err := http.NewRequestWithContext(ctx, "{{ .Method }}", requestURL{{ if .HasRequestBody }}, body{{ else }}, nil{{ end }})
	if err != nil {
		return {{ retPrefix .HasResponse }}fmt.Errorf("create request: %w", err)
	}
{{- if .HasRequestBody }}
	httpReq.Header.Set("Content-Type", "application/json")
{{- end }}
{{- range .HeaderParams }}
	httpReq.Header.Set("{{ .Name }}", fmt.Sprintf("%v", input.{{ .GoFieldName }}))
{{- end }}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return {{ retPrefix .HasResponse }}fmt.Errorf("execute request: %w", err)
	}

{{- if .HasResponse }}
	return &{{ .MethodName }}Response{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
{{- else }}
	defer httpResp.Body.Close()
	if httpResp.StatusCode >= 400 {
		rawBody, _ := io.ReadAll(httpResp.Body)
		return fmt.Errorf("request failed: status %d, body: %s", httpResp.StatusCode, string(rawBody))
	}
	return nil
{{- end }}
}

{{- end }}

{{- /* Response types for this tag's operations */ -}}
{{- range .Operations }}
{{- if .HasResponse }}
{{- $methodName := .MethodName }}

// {{ $methodName }}Response is the response for the {{ $methodName }} operation.
// Call Close() when done to release the response body.
type {{ $methodName }}Response struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
{{- range $status, $field := .ResponseBody.Fields }}
	status{{ $field.StatusCode }} *{{ $field.GoType }}
{{- end }}
}

// Close releases the response body. Always call when done.
func (r *{{ $methodName }}Response) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// If the body was cached (via StatusOk or a prior read), each call
// returns a reset reader so the body can be read multiple times.
func (r *{{ $methodName }}Response) Body() io.ReadCloser {
	if r.resp == nil {
		return nil
	}
	if seeker, ok := r.resp.Body.(io.Seeker); ok {
		seeker.Seek(0, io.SeekStart)
	}
	return r.resp.Body
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It streams directly from resp.Body without caching, so the body is consumed.
// Do not call StatusOk() or Body() after Stream() — the body will be exhausted.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *{{ $methodName }}Response) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if r.resp == nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// (bytes.Reader wrapped as io.ReadCloser) so subsequent reads can reuse the data.
func (r *{{ $methodName }}Response) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = nooaclient.NewCachedBodyReader(data)
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *{{ $methodName }}Response) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

{{- range $status, $field := .ResponseBody.Fields }}

// Status{{ toGoTypeName (printf "%d" $field.StatusCode) }} returns the unmarshaled response body for status {{ $field.StatusCode }}.
func (r *{{ $methodName }}Response) Status{{ toGoTypeName (printf "%d" $field.StatusCode) }}() (*{{ $field.GoType }}, error) {
	if r.status{{ $field.StatusCode }} != nil {
		return r.status{{ $field.StatusCode }}, nil
	}
	if r.StatusCode() != {{ $field.StatusCode }} {
		return nil, fmt.Errorf("expected status {{ $field.StatusCode }}, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status{{ $field.StatusCode }} = new({{ $field.GoType }})
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status{{ $field.StatusCode }}); err != nil {
		return nil, err
	}
	return r.status{{ $field.StatusCode }}, nil
}

{{- end }}
{{- end }}
{{- end }}
