// Code generated by clientgen. DO NOT EDIT.
// Source: 12 Custom Types Demo v1.0.0

package customtypesdemo

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"bytes"
	customtypes "github.com/arkannsk/nooa/examples/models/12_custom_types"
)

// HTTPClient is the interface that wraps the Do method.
// It is compatible with *http.Client and useful for testing.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client is the generated HTTP client for 12 Custom Types Demo.
type Client struct {
	BaseURL     string
	HTTPClient  HTTPClient
	Token       string
	TokenPrefix string
}

// New creates a new Client.
func New(baseURL string, hc HTTPClient) *Client {
	if hc == nil {
		hc = &http.Client{}
	}
	return &Client{
		BaseURL:     strings.TrimRight(baseURL, "/"),
		HTTPClient:  hc,
		TokenPrefix: "Bearer",
	}
}


// Type aliases with validation
// POST /aliases


// POSTAliasesRequest holds parameters for POSTAliases.
type POSTAliasesRequest struct {
	// Body is the request body.
	Body customtypes.WithAliases
}

// POSTAliasesResponse holds the response for POSTAliases.
type POSTAliasesResponse struct {
	// Status 200 — 12_custom_types.WithAliases
	Status200 customtypes.WithAliases
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// POSTAliases — Type aliases with validation
func (c *Client) POSTAliases(ctx context.Context, input *POSTAliasesRequest) (*POSTAliasesResponse, error) {

	u := c.BaseURL + "/aliases"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &POSTAliasesResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Custom reader as file
// POST /custom-reader


// POSTCustomreaderResponse holds the response for POSTCustomreader.
type POSTCustomreaderResponse struct {
	// Status 200 — 12_custom_types.WithCustomReader
	Status200 customtypes.WithCustomReader
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// POSTCustomreader — Custom reader as file
func (c *Client) POSTCustomreader(ctx context.Context) (*POSTCustomreaderResponse, error) {

	u := c.BaseURL + "/custom-reader"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &POSTCustomreaderResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Embedded struct
// GET /embed


// GETEmbedResponse holds the response for GETEmbed.
type GETEmbedResponse struct {
	// Status 200 — 12_custom_types.WithEmbed
	Status200 customtypes.WithEmbed
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETEmbed — Embedded struct
func (c *Client) GETEmbed(ctx context.Context) (*GETEmbedResponse, error) {

	u := c.BaseURL + "/embed"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETEmbedResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



