// Code generated by clientgen. DO NOT EDIT.
// Source: 12 Custom Types Demo v1.0.0

package customtypesdemo

import (
	"context"
	"net/http"
	"strings"
	"fmt"
	"io"
	"sync"
	"bytes"
	"encoding/json"
	nooaclient "github.com/arkannsk/nooa/client"
	customtypes "github.com/arkannsk/nooa/examples/models/12_custom_types"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// httpc is the internal HTTP client shared by all tag adapters.
type httpc struct {
	BaseURL    string
	HTTPClient HTTPClient
	Codec      map[string]nooaclient.Codec
}

func newHTTPC(baseURL string, hc any) *httpc {
	var httpClient HTTPClient
	switch v := hc.(type) {
	case nil:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		httpClient = &stdHTTPClient{Client: v}
	case HTTPClient:
		httpClient = v
	default:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	}
	return &httpc{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: httpClient,
	}
}
// V1 is the HTTP client for 12 Custom Types Demo.
type V1 struct {
	base *httpc
}

// New creates a new V1 client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *V1 {
	return &V1{base: newHTTPC(baseURL, hc)}
}

// Type aliases with validation
// POST /aliases
func (c *V1) POSTAliases(ctx context.Context, input *customtypes.WithAliases) (*POSTAliasesResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/aliases"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &POSTAliasesResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// Custom reader as file
// POST /custom-reader
func (c *V1) POSTCustomreader(ctx context.Context, input *customtypes.WithCustomReader) (*POSTCustomreaderResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/custom-reader"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &POSTCustomreaderResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// Embedded struct
// GET /embed
func (c *V1) GETEmbed(ctx context.Context, input *customtypes.WithEmbed) (*GETEmbedResponse, error) {

	path := "/embed"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETEmbedResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// POSTAliasesResponse is the response for the POSTAliases operation.
// Call Close() when done to release the response body.
type POSTAliasesResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *customtypes.WithAliases
}

// Close releases the response body. Always call when done.
func (r *POSTAliasesResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// If the body was cached (via StatusOk or a prior read), each call
// returns a reset reader so the body can be read multiple times.
func (r *POSTAliasesResponse) Body() io.ReadCloser {
	if r.resp == nil {
		return nil
	}
	if seeker, ok := r.resp.Body.(io.Seeker); ok {
		seeker.Seek(0, io.SeekStart)
	}
	return r.resp.Body
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It streams directly from resp.Body without caching, so the body is consumed.
// Do not call StatusOk() or Body() after Stream() — the body will be exhausted.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *POSTAliasesResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if r.resp == nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// (bytes.Reader wrapped as io.ReadCloser) so subsequent reads can reuse the data.
func (r *POSTAliasesResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = nooaclient.NewCachedBodyReader(data)
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *POSTAliasesResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *POSTAliasesResponse) StatusOk() (*customtypes.WithAliases, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(customtypes.WithAliases)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// POSTCustomreaderResponse is the response for the POSTCustomreader operation.
// Call Close() when done to release the response body.
type POSTCustomreaderResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *customtypes.WithCustomReader
}

// Close releases the response body. Always call when done.
func (r *POSTCustomreaderResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// If the body was cached (via StatusOk or a prior read), each call
// returns a reset reader so the body can be read multiple times.
func (r *POSTCustomreaderResponse) Body() io.ReadCloser {
	if r.resp == nil {
		return nil
	}
	if seeker, ok := r.resp.Body.(io.Seeker); ok {
		seeker.Seek(0, io.SeekStart)
	}
	return r.resp.Body
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It streams directly from resp.Body without caching, so the body is consumed.
// Do not call StatusOk() or Body() after Stream() — the body will be exhausted.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *POSTCustomreaderResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if r.resp == nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// (bytes.Reader wrapped as io.ReadCloser) so subsequent reads can reuse the data.
func (r *POSTCustomreaderResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = nooaclient.NewCachedBodyReader(data)
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *POSTCustomreaderResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *POSTCustomreaderResponse) StatusOk() (*customtypes.WithCustomReader, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(customtypes.WithCustomReader)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETEmbedResponse is the response for the GETEmbed operation.
// Call Close() when done to release the response body.
type GETEmbedResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *customtypes.WithEmbed
}

// Close releases the response body. Always call when done.
func (r *GETEmbedResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// If the body was cached (via StatusOk or a prior read), each call
// returns a reset reader so the body can be read multiple times.
func (r *GETEmbedResponse) Body() io.ReadCloser {
	if r.resp == nil {
		return nil
	}
	if seeker, ok := r.resp.Body.(io.Seeker); ok {
		seeker.Seek(0, io.SeekStart)
	}
	return r.resp.Body
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It streams directly from resp.Body without caching, so the body is consumed.
// Do not call StatusOk() or Body() after Stream() — the body will be exhausted.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *GETEmbedResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if r.resp == nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// (bytes.Reader wrapped as io.ReadCloser) so subsequent reads can reuse the data.
func (r *GETEmbedResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = nooaclient.NewCachedBodyReader(data)
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETEmbedResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETEmbedResponse) StatusOk() (*customtypes.WithEmbed, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(customtypes.WithEmbed)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
