// Code generated by clientgen. DO NOT EDIT.
// Source: 12 Custom Types Demo v1.0.0

package customtypesdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"bytes"
	"encoding/json"
	"strings"
	"github.com/arkannsk/nooa/client"
	customtypes "github.com/arkannsk/nooa/examples/models/12_custom_types"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// Client is the generated HTTP client for 12 Custom Types Demo.
type Client struct {
	BaseURL    string
	HTTPClient HTTPClient

	// Codec maps Content-Type to client.Codec for response body decoding.
	// If nil, defaults to JSON decoding for all types.
	Codec map[string]client.Codec
}

// New creates a new Client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *Client {
	var client HTTPClient
	switch v := hc.(type) {
	case nil:
		client = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		client = &stdHTTPClient{Client: v}
	case HTTPClient:
		client = v
	default:
		client = &stdHTTPClient{Client: &http.Client{}}
	}
	return &Client{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: client,
	}
}


// Type aliases with validation
// POST /aliases


// POSTAliasesRequest holds parameters for POSTAliases.
type POSTAliasesRequest struct {
	// Body is the request body.
	Body customtypes.WithAliases
}

// POSTAliasesResponse holds the response for POSTAliases.
type POSTAliasesResponse struct {
	*http.Response
	client *Client
	status200 *customtypes.WithAliases
}

func (r *POSTAliasesResponse) StatusOk() (*customtypes.WithAliases, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(customtypes.WithAliases)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// POSTAliases — Type aliases with validation
func (c *Client) POSTAliases(ctx context.Context, input *POSTAliasesRequest) (*POSTAliasesResponse, error) {

	u := c.BaseURL + "/aliases"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &POSTAliasesResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Custom reader as file
// POST /custom-reader


// POSTCustomreaderRequest holds parameters for POSTCustomreader.
type POSTCustomreaderRequest struct {
	// Body is the request body.
	Body customtypes.WithCustomReader
}

// POSTCustomreaderResponse holds the response for POSTCustomreader.
type POSTCustomreaderResponse struct {
	*http.Response
	client *Client
	status200 *customtypes.WithCustomReader
}

func (r *POSTCustomreaderResponse) StatusOk() (*customtypes.WithCustomReader, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(customtypes.WithCustomReader)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// POSTCustomreader — Custom reader as file
func (c *Client) POSTCustomreader(ctx context.Context, input *POSTCustomreaderRequest) (*POSTCustomreaderResponse, error) {

	u := c.BaseURL + "/custom-reader"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &POSTCustomreaderResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Embedded struct
// GET /embed


// GETEmbedResponse holds the response for GETEmbed.
type GETEmbedResponse struct {
	*http.Response
	client *Client
	status200 *customtypes.WithEmbed
}

func (r *GETEmbedResponse) StatusOk() (*customtypes.WithEmbed, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(customtypes.WithEmbed)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETEmbed — Embedded struct
func (c *Client) GETEmbed(ctx context.Context) (*GETEmbedResponse, error) {

	u := c.BaseURL + "/embed"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &GETEmbedResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



