// Code generated by clientgen. DO NOT EDIT.
// Source: 08 HTTP Parameters Demo v1.0.0

package httpparametersdemo

import (
	"context"
	"net/http"
	"strings"
	"fmt"
	"io"
	"net/url"
	"bytes"
	"encoding/json"
	nooaclient "github.com/arkannsk/nooa/client"
	httpparams "github.com/arkannsk/nooa/examples/models/08_http_params"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// httpc is the internal HTTP client shared by all tag adapters.
type httpc struct {
	BaseURL    string
	HTTPClient HTTPClient
	Codec      map[string]nooaclient.Codec
}

func newHTTPC(baseURL string, hc any) *httpc {
	var httpClient HTTPClient
	switch v := hc.(type) {
	case nil:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		httpClient = &stdHTTPClient{Client: v}
	case HTTPClient:
		httpClient = v
	default:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	}
	return &httpc{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: httpClient,
	}
}
// V1 is the HTTP client for 08 HTTP Parameters Demo.
type V1 struct {
	base *httpc
}

// New creates a new V1 client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *V1 {
	return &V1{base: newHTTPC(baseURL, hc)}
}

// Request with header parameters
// POST /header-demo
func (c *V1) POSTHeaderdemo(ctx context.Context, input *httpparams.HeaderParams) (*POSTHeaderdemoResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/header-demo"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("X-API-Key", fmt.Sprintf("%v", input.APIKey))
	httpReq.Header.Set("request-id", fmt.Sprintf("%v", input.RequestID))

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &POSTHeaderdemoResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Mixed parameter locations
// GET /items/{id}
func (c *V1) GETItemsId(ctx context.Context, input *httpparams.MixedParams) (*GETItemsIdResponse, error) {

	path := "/items/{id}"
	path = strings.ReplaceAll(path, "{id}", fmt.Sprintf("%v", input.ID))

	requestURL := c.base.BaseURL + path
	queryValues := url.Values{}
	if input.Filter != "" {
		queryValues.Add("filter", input.Filter)
	}
	if len(queryValues) > 0 {
		requestURL += "?" + queryValues.Encode()
	}

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("X-Auth-Token", fmt.Sprintf("%v", input.AuthToken))

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETItemsIdResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Search with query parameters
// GET /search
func (c *V1) GETSearch(ctx context.Context, input *httpparams.QueryParams) (*GETSearchResponse, error) {

	path := "/search"

	requestURL := c.base.BaseURL + path
	queryValues := url.Values{}
	if input.Query != "" {
		queryValues.Add("query", input.Query)
	}
	if input.Page != 0 {
		queryValues.Add("page", fmt.Sprintf("%v", input.Page))
	}
	if input.Limit != 0 {
		queryValues.Add("limit", fmt.Sprintf("%v", input.Limit))
	}
	if input.Status != "" {
		queryValues.Add("status", input.Status)
	}
	if len(queryValues) > 0 {
		requestURL += "?" + queryValues.Encode()
	}

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETSearchResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Update resource by path parameters
// PUT /users/{userId}/resources/{resource_id}
func (c *V1) PUTUsersUserIdResourcesResourceid(ctx context.Context, input *httpparams.PathParams) (*PUTUsersUserIdResourcesResourceidResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/users/{userId}/resources/{resource_id}"
	path = strings.ReplaceAll(path, "{userId}", fmt.Sprintf("%v", input.UserID))
	path = strings.ReplaceAll(path, "{resource_id}", fmt.Sprintf("%v", input.ResourceID))

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "PUT", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &PUTUsersUserIdResourcesResourceidResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// POSTHeaderdemoResponse is the response for the POSTHeaderdemo operation.
type POSTHeaderdemoResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *httpparams.HeaderParams
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *POSTHeaderdemoResponse) StatusOk() (*httpparams.HeaderParams, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(httpparams.HeaderParams)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETItemsIdResponse is the response for the GETItemsId operation.
type GETItemsIdResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *httpparams.MixedParams
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETItemsIdResponse) StatusOk() (*httpparams.MixedParams, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(httpparams.MixedParams)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETSearchResponse is the response for the GETSearch operation.
type GETSearchResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *httpparams.QueryParams
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETSearchResponse) StatusOk() (*httpparams.QueryParams, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(httpparams.QueryParams)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// PUTUsersUserIdResourcesResourceidResponse is the response for the PUTUsersUserIdResourcesResourceid operation.
type PUTUsersUserIdResourcesResourceidResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *httpparams.PathParams
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *PUTUsersUserIdResourcesResourceidResponse) StatusOk() (*httpparams.PathParams, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(httpparams.PathParams)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
