// Code generated by elval-gen. DO NOT EDIT.
// Source: edge.go

package edgecases

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *EmptyStruct) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 0),
		Required:   make([]string, 0, 0),
		Ref:        v.GlobalRef(),
	}

	return schema
}

func (v *EmptyStruct) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/11_edge_cases.EmptyStruct"
}

func (v *PointerChain) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Description = "String pointer"

		schema.Properties["level1"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Description = "Pointer to pointer"

		schema.Properties["level2"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/github.com/arkannsk/nooa/examples/models/11_edge_cases.Nested"

		prop.Description = "Pointer to struct"

		schema.Properties["level3"] = prop
	}

	return schema
}

func (v *PointerChain) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/11_edge_cases.PointerChain"
}

func (v *Nested) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["value"] = prop
	}

	return schema
}

func (v *Nested) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/11_edge_cases.Nested"
}

func (v *CircularRefA) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/github.com/arkannsk/nooa/examples/models/11_edge_cases.CircularRefB"

		prop.Description = "Reference to B"

		schema.Properties["b"] = prop
	}

	return schema
}

func (v *CircularRefA) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/11_edge_cases.CircularRefA"
}

func (v *CircularRefB) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/github.com/arkannsk/nooa/examples/models/11_edge_cases.CircularRefA"

		prop.Description = "Reference to A"

		schema.Properties["a"] = prop
	}

	return schema
}

func (v *CircularRefB) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/11_edge_cases.CircularRefB"
}

func (v *WithInterface) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Description = "Flexible value"
		prop.OneOf = []*oa.Schema{
			{Ref: "#/components/schemas/github.com/arkannsk/nooa/examples/models/11_edge_cases.StringValue"},
			{Ref: "#/components/schemas/github.com/arkannsk/nooa/examples/models/11_edge_cases.NumberValue"},
		}

		schema.Properties["data"] = prop
	}

	return schema
}

func (v *WithInterface) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/11_edge_cases.WithInterface"
}

func (v *WithUntypedNil) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Description = "Nullable string"

		schema.Properties["optional"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/github.com/arkannsk/nooa/examples/models/11_edge_cases.Nested"

		prop.Description = "Nullable struct"

		schema.Properties["child"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Description = "Nullable slice"

		schema.Properties["items"] = prop
	}

	return schema
}

func (v *WithUntypedNil) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/11_edge_cases.WithUntypedNil"
}
