// Code generated by clientgen. DO NOT EDIT.
// Source: 09 Ignore Demo v1.0.0

package ignoredemo

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	ignore "github.com/arkannsk/nooa/examples/models/09_ignore"
)

// HTTPClient is the interface that wraps the Do method.
// It is compatible with *http.Client and useful for testing.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client is the generated HTTP client for 09 Ignore Demo.
type Client struct {
	BaseURL     string
	HTTPClient  HTTPClient
	Token       string
	TokenPrefix string
}

// New creates a new Client.
func New(baseURL string, hc HTTPClient) *Client {
	if hc == nil {
		hc = &http.Client{}
	}
	return &Client{
		BaseURL:     strings.TrimRight(baseURL, "/"),
		HTTPClient:  hc,
		TokenPrefix: "Bearer",
	}
}


// Struct with an ignored field
// GET /ignored-field


// GETIgnoredfieldResponse holds the response for GETIgnoredfield.
type GETIgnoredfieldResponse struct {
	// Status 200 — ign.WithIgnoredField
	Status200 ignore.WithIgnoredField
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETIgnoredfield — Struct with an ignored field
func (c *Client) GETIgnoredfield(ctx context.Context) (*GETIgnoredfieldResponse, error) {

	u := c.BaseURL + "/ignored-field"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETIgnoredfieldResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Struct with all fields ignored
// GET /only-ignored


// GETOnlyignoredResponse holds the response for GETOnlyignored.
type GETOnlyignoredResponse struct {
	// Status 200 — ign.OnlyIgnoredFields
	Status200 ignore.OnlyIgnoredFields
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETOnlyignored — Struct with all fields ignored
func (c *Client) GETOnlyignored(ctx context.Context) (*GETOnlyignoredResponse, error) {

	u := c.BaseURL + "/only-ignored"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETOnlyignoredResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Field overrides ignored type
// GET /override


// GETOverrideResponse holds the response for GETOverride.
type GETOverrideResponse struct {
	// Status 200 — ign.WithOverride
	Status200 ignore.WithOverride
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETOverride — Field overrides ignored type
func (c *Client) GETOverride(ctx context.Context) (*GETOverrideResponse, error) {

	u := c.BaseURL + "/override"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETOverrideResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



