// Code generated by clientgen. DO NOT EDIT.
// Source: 10 Validators Demo v1.0.0

package validatorsdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"bytes"
	"encoding/json"
	"strings"
	"github.com/arkannsk/nooa/client"
	validators "github.com/arkannsk/nooa/examples/models/10_validators"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// Client is the generated HTTP client for 10 Validators Demo.
type Client struct {
	BaseURL    string
	HTTPClient HTTPClient

	// Codec maps Content-Type to client.Codec for response body decoding.
	// If nil, defaults to JSON decoding for all types.
	Codec map[string]client.Codec
}

// New creates a new Client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *Client {
	var client HTTPClient
	switch v := hc.(type) {
	case nil:
		client = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		client = &stdHTTPClient{Client: v}
	case HTTPClient:
		client = v
	default:
		client = &stdHTTPClient{Client: &http.Client{}}
	}
	return &Client{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: client,
	}
}


// Validate date and duration fields
// POST /validate/date


// POSTValidateDateRequest holds parameters for POSTValidateDate.
type POSTValidateDateRequest struct {
	// Body is the request body.
	Body validators.DateAndDurationValidators
}

// POSTValidateDateResponse holds the response for POSTValidateDate.
type POSTValidateDateResponse struct {
	*http.Response
	client *Client
	status200 *validators.DateAndDurationValidators
}

func (r *POSTValidateDateResponse) StatusOk() (*validators.DateAndDurationValidators, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(validators.DateAndDurationValidators)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// POSTValidateDate — Validate date and duration fields
func (c *Client) POSTValidateDate(ctx context.Context, input *POSTValidateDateRequest) (*POSTValidateDateResponse, error) {

	u := c.BaseURL + "/validate/date"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &POSTValidateDateResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Validate enum and slice fields
// POST /validate/enum-slice


// POSTValidateEnumsliceRequest holds parameters for POSTValidateEnumslice.
type POSTValidateEnumsliceRequest struct {
	// Body is the request body.
	Body validators.AllEnumAndSliceValidators
}

// POSTValidateEnumsliceResponse holds the response for POSTValidateEnumslice.
type POSTValidateEnumsliceResponse struct {
	*http.Response
	client *Client
	status200 *validators.AllEnumAndSliceValidators
}

func (r *POSTValidateEnumsliceResponse) StatusOk() (*validators.AllEnumAndSliceValidators, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(validators.AllEnumAndSliceValidators)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// POSTValidateEnumslice — Validate enum and slice fields
func (c *Client) POSTValidateEnumslice(ctx context.Context, input *POSTValidateEnumsliceRequest) (*POSTValidateEnumsliceResponse, error) {

	u := c.BaseURL + "/validate/enum-slice"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &POSTValidateEnumsliceResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Validate numeric fields
// POST /validate/numeric


// POSTValidateNumericRequest holds parameters for POSTValidateNumeric.
type POSTValidateNumericRequest struct {
	// Body is the request body.
	Body validators.AllNumericValidators
}

// POSTValidateNumericResponse holds the response for POSTValidateNumeric.
type POSTValidateNumericResponse struct {
	*http.Response
	client *Client
	status200 *validators.AllNumericValidators
}

func (r *POSTValidateNumericResponse) StatusOk() (*validators.AllNumericValidators, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(validators.AllNumericValidators)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// POSTValidateNumeric — Validate numeric fields
func (c *Client) POSTValidateNumeric(ctx context.Context, input *POSTValidateNumericRequest) (*POSTValidateNumericResponse, error) {

	u := c.BaseURL + "/validate/numeric"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &POSTValidateNumericResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Validate string fields
// POST /validate/string


// POSTValidateStringRequest holds parameters for POSTValidateString.
type POSTValidateStringRequest struct {
	// Body is the request body.
	Body validators.AllStringValidators
}

// POSTValidateStringResponse holds the response for POSTValidateString.
type POSTValidateStringResponse struct {
	*http.Response
	client *Client
	status200 *validators.AllStringValidators
}

func (r *POSTValidateStringResponse) StatusOk() (*validators.AllStringValidators, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(validators.AllStringValidators)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// POSTValidateString — Validate string fields
func (c *Client) POSTValidateString(ctx context.Context, input *POSTValidateStringRequest) (*POSTValidateStringResponse, error) {

	u := c.BaseURL + "/validate/string"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &POSTValidateStringResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



