// Code generated by clientgen. DO NOT EDIT.
// Source: 06 Polymorphism Demo v1.0.0

package polymorphismdemo

import (
	"context"
	"net/http"
	"strings"
	nooaclient "github.com/arkannsk/nooa/client"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// httpc is the internal HTTP client shared by all tag adapters.
type httpc struct {
	BaseURL    string
	HTTPClient HTTPClient
	Codec      map[string]nooaclient.Codec
}

func newHTTPC(baseURL string, hc any) *httpc {
	var httpClient HTTPClient
	switch v := hc.(type) {
	case nil:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		httpClient = &stdHTTPClient{Client: v}
	case HTTPClient:
		httpClient = v
	default:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	}
	return &httpc{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: httpClient,
	}
}
// V1 is the top-level client for 06 Polymorphism Demo.
// It provides tag-scoped sub-clients for each API group.
type V1 struct {
	// Polymorphism provides access to the "Polymorphism" operations.
	Polymorphism PolymorphismClient
	// Shapes provides access to the "Shapes" operations.
	Shapes ShapesClient
}

// New creates a new V1 client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *V1 {
	c := newHTTPC(baseURL, hc)
	return &V1{
		Polymorphism: &polymorphismAdapter{httpc: c},
		Shapes: &shapesAdapter{httpc: c},
	}
}
