// Code generated by clientgen. DO NOT EDIT.
// Source: 06 Polymorphism Demo v1.0.0

package polymorphismdemo

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"sync"
	nooaclient "github.com/arkannsk/nooa/client"
	polymorphism "github.com/arkannsk/nooa/examples/models/06_polymorphism"
)

// PolymorphismClient groups the Polymorphism operations.
type PolymorphismClient interface {
	GETContainer(ctx context.Context, input *polymorphism.Container) (*GETContainerResponse, error)
	GETOneof(ctx context.Context, input *polymorphism.OneOfExample) (*GETOneofResponse, error)
}

// polymorphismAdapter implements PolymorphismClient.
type polymorphismAdapter struct {
	httpc *httpc
}

// Get container with shape
// GET /container
func (t *polymorphismAdapter) GETContainer(ctx context.Context, input *polymorphism.Container) (*GETContainerResponse, error) {

	path := "/container"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETContainerResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// Get oneOf example
// GET /oneof
func (t *polymorphismAdapter) GETOneof(ctx context.Context, input *polymorphism.OneOfExample) (*GETOneofResponse, error) {

	path := "/oneof"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETOneofResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// GETContainerResponse is the response for the GETContainer operation.
// Call Close() when done to release the response body.
type GETContainerResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *polymorphism.Container
}

// Close releases the response body. Always call when done.
func (r *GETContainerResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETContainerResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It reads the body once and caches it, so subsequent calls return a reader over the same data.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *GETContainerResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if err := r.readBody(); err != nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETContainerResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETContainerResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETContainerResponse) StatusOk() (*polymorphism.Container, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(polymorphism.Container)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETOneofResponse is the response for the GETOneof operation.
// Call Close() when done to release the response body.
type GETOneofResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *polymorphism.OneOfExample
}

// Close releases the response body. Always call when done.
func (r *GETOneofResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETOneofResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It reads the body once and caches it, so subsequent calls return a reader over the same data.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *GETOneofResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if err := r.readBody(); err != nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETOneofResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETOneofResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETOneofResponse) StatusOk() (*polymorphism.OneOfExample, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(polymorphism.OneOfExample)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
