// Code generated by clientgen. DO NOT EDIT.
// Source: 06 Polymorphism Demo v1.0.0

package polymorphismdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	nooaclient "github.com/arkannsk/nooa/client"
	polymorphism "github.com/arkannsk/nooa/examples/models/06_polymorphism"
)

// PolymorphismClient groups the Polymorphism operations.
type PolymorphismClient interface {
	GETContainer(ctx context.Context, input *polymorphism.Container) (*GETContainerResponse, error)
	GETOneof(ctx context.Context, input *polymorphism.OneOfExample) (*GETOneofResponse, error)
}

// polymorphismAdapter implements PolymorphismClient.
type polymorphismAdapter struct {
	httpc *httpc
}

// Get container with shape
// GET /container
func (t *polymorphismAdapter) GETContainer(ctx context.Context, input *polymorphism.Container) (*GETContainerResponse, error) {

	path := "/container"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETContainerResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// Get oneOf example
// GET /oneof
func (t *polymorphismAdapter) GETOneof(ctx context.Context, input *polymorphism.OneOfExample) (*GETOneofResponse, error) {

	path := "/oneof"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETOneofResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// GETContainerResponse is the response for the GETContainer operation.
type GETContainerResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *polymorphism.Container
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETContainerResponse) StatusOk() (*polymorphism.Container, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(polymorphism.Container)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETOneofResponse is the response for the GETOneof operation.
type GETOneofResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *polymorphism.OneOfExample
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETOneofResponse) StatusOk() (*polymorphism.OneOfExample, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(polymorphism.OneOfExample)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
