// Code generated by clientgen. DO NOT EDIT.
// Source: 06 Polymorphism Demo v1.0.0

package polymorphismdemo

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"sync"
	nooaclient "github.com/arkannsk/nooa/client"
	polymorphism "github.com/arkannsk/nooa/examples/models/06_polymorphism"
)

// ShapesClient groups the Shapes operations.
type ShapesClient interface {
	GETCircle(ctx context.Context, input *polymorphism.CircleShape) (*GETCircleResponse, error)
	GETRectangle(ctx context.Context, input *polymorphism.RectangleShape) (*GETRectangleResponse, error)
}

// shapesAdapter implements ShapesClient.
type shapesAdapter struct {
	httpc *httpc
}

// Get circle shape
// GET /circle
func (t *shapesAdapter) GETCircle(ctx context.Context, input *polymorphism.CircleShape) (*GETCircleResponse, error) {

	path := "/circle"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETCircleResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// Get rectangle shape
// GET /rectangle
func (t *shapesAdapter) GETRectangle(ctx context.Context, input *polymorphism.RectangleShape) (*GETRectangleResponse, error) {

	path := "/rectangle"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETRectangleResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// GETCircleResponse is the response for the GETCircle operation.
// Call Close() when done to release the response body.
type GETCircleResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *polymorphism.CircleShape
}

// Close releases the response body. Always call when done.
func (r *GETCircleResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETCircleResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETCircleResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETCircleResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETCircleResponse) StatusOk() (*polymorphism.CircleShape, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(polymorphism.CircleShape)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETRectangleResponse is the response for the GETRectangle operation.
// Call Close() when done to release the response body.
type GETRectangleResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *polymorphism.RectangleShape
}

// Close releases the response body. Always call when done.
func (r *GETRectangleResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETRectangleResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETRectangleResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETRectangleResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETRectangleResponse) StatusOk() (*polymorphism.RectangleShape, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(polymorphism.RectangleShape)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
