// Code generated by clientgen. DO NOT EDIT.
// Source: 06 Polymorphism Demo v1.0.0

package polymorphismdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	nooaclient "github.com/arkannsk/nooa/client"
	polymorphism "github.com/arkannsk/nooa/examples/models/06_polymorphism"
)

// ShapesClient groups the Shapes operations.
type ShapesClient interface {
	GETCircle(ctx context.Context, input *polymorphism.CircleShape) (*GETCircleResponse, error)
	GETRectangle(ctx context.Context, input *polymorphism.RectangleShape) (*GETRectangleResponse, error)
}

// shapesAdapter implements ShapesClient.
type shapesAdapter struct {
	httpc *httpc
}

// Get circle shape
// GET /circle
func (t *shapesAdapter) GETCircle(ctx context.Context, input *polymorphism.CircleShape) (*GETCircleResponse, error) {

	path := "/circle"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETCircleResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// Get rectangle shape
// GET /rectangle
func (t *shapesAdapter) GETRectangle(ctx context.Context, input *polymorphism.RectangleShape) (*GETRectangleResponse, error) {

	path := "/rectangle"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETRectangleResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// GETCircleResponse is the response for the GETCircle operation.
type GETCircleResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *polymorphism.CircleShape
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETCircleResponse) StatusOk() (*polymorphism.CircleShape, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(polymorphism.CircleShape)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETRectangleResponse is the response for the GETRectangle operation.
type GETRectangleResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *polymorphism.RectangleShape
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETRectangleResponse) StatusOk() (*polymorphism.RectangleShape, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(polymorphism.RectangleShape)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
