// Code generated by clientgen. DO NOT EDIT.
// Source: 01 Basic Types Demo v1.0.0

package basictypesdemo

import (
	"context"
	"net/http"
	"strings"
	"fmt"
	"io"
	"bytes"
	"encoding/json"
	nooaclient "github.com/arkannsk/nooa/client"
	basictypes "github.com/arkannsk/nooa/examples/models/01_basic_types"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// httpc is the internal HTTP client shared by all tag adapters.
type httpc struct {
	BaseURL    string
	HTTPClient HTTPClient
	Codec      map[string]nooaclient.Codec
}

func newHTTPC(baseURL string, hc any) *httpc {
	var httpClient HTTPClient
	switch v := hc.(type) {
	case nil:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		httpClient = &stdHTTPClient{Client: v}
	case HTTPClient:
		httpClient = v
	default:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	}
	return &httpc{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: httpClient,
	}
}
// V1 is the HTTP client for 01 Basic Types Demo.
type V1 struct {
	base *httpc
}

// New creates a new V1 client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *V1 {
	return &V1{base: newHTTPC(baseURL, hc)}
}

// Create with default values
// POST /defaults
func (c *V1) POSTDefaults(ctx context.Context, input *basictypes.WithDefaults) (*POSTDefaultsResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/defaults"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &POSTDefaultsResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Get nullable pointer fields
// GET /pointers
func (c *V1) GETPointers(ctx context.Context, input *basictypes.WithPointers) (*GETPointersResponse, error) {

	path := "/pointers"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETPointersResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Create with primitive types
// POST /primitives
func (c *V1) POSTPrimitives(ctx context.Context, input *basictypes.SimplePrimitives) (*POSTPrimitivesResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/primitives"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &POSTPrimitivesResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// POSTDefaultsResponse is the response for the POSTDefaults operation.
type POSTDefaultsResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status201 *basictypes.WithDefaults
}

// StatusCreated returns the unmarshaled response body for status 201.
func (r *POSTDefaultsResponse) StatusCreated() (*basictypes.WithDefaults, error) {
	if r.status201 != nil {
		return r.status201, nil
	}
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status201 = new(basictypes.WithDefaults)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// GETPointersResponse is the response for the GETPointers operation.
type GETPointersResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *basictypes.WithPointers
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETPointersResponse) StatusOk() (*basictypes.WithPointers, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(basictypes.WithPointers)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// POSTPrimitivesResponse is the response for the POSTPrimitives operation.
type POSTPrimitivesResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status201 *basictypes.SimplePrimitives
}

// StatusCreated returns the unmarshaled response body for status 201.
func (r *POSTPrimitivesResponse) StatusCreated() (*basictypes.SimplePrimitives, error) {
	if r.status201 != nil {
		return r.status201, nil
	}
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status201 = new(basictypes.SimplePrimitives)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}
