// Code generated by clientgen. DO NOT EDIT.
// Source: 01 Basic Types Demo v1.0.0

package basictypesdemo

import (
	"context"
	"net/http"
	"strings"
	"bytes"
	"fmt"
	"io"
	"sync"
	"encoding/json"
	nooaclient "github.com/arkannsk/nooa/client"
	basictypes "github.com/arkannsk/nooa/examples/models/01_basic_types"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// httpc is the internal HTTP client shared by all tag adapters.
type httpc struct {
	BaseURL    string
	HTTPClient HTTPClient
	Codec      map[string]nooaclient.Codec
}

func newHTTPC(baseURL string, hc any) *httpc {
	var httpClient HTTPClient
	switch v := hc.(type) {
	case nil:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		httpClient = &stdHTTPClient{Client: v}
	case HTTPClient:
		httpClient = v
	default:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	}
	return &httpc{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: httpClient,
	}
}
// V1 is the HTTP client for 01 Basic Types Demo.
type V1 struct {
	base *httpc
}

// New creates a new V1 client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *V1 {
	return &V1{base: newHTTPC(baseURL, hc)}
}

// Create with default values
// POST /defaults
func (c *V1) POSTDefaults(ctx context.Context, input *basictypes.WithDefaults) (*POSTDefaultsResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/defaults"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &POSTDefaultsResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// Get nullable pointer fields
// GET /pointers
func (c *V1) GETPointers(ctx context.Context, input *basictypes.WithPointers) (*GETPointersResponse, error) {

	path := "/pointers"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETPointersResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// Create with primitive types
// POST /primitives
func (c *V1) POSTPrimitives(ctx context.Context, input *basictypes.SimplePrimitives) (*POSTPrimitivesResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/primitives"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &POSTPrimitivesResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// POSTDefaultsResponse is the response for the POSTDefaults operation.
// Call Close() when done to release the response body.
type POSTDefaultsResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status201 *basictypes.WithDefaults
}

// Close releases the response body. Always call when done.
func (r *POSTDefaultsResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *POSTDefaultsResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *POSTDefaultsResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *POSTDefaultsResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusCreated returns the unmarshaled response body for status 201.
func (r *POSTDefaultsResponse) StatusCreated() (*basictypes.WithDefaults, error) {
	if r.status201 != nil {
		return r.status201, nil
	}
	if r.StatusCode() != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status201 = new(basictypes.WithDefaults)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// GETPointersResponse is the response for the GETPointers operation.
// Call Close() when done to release the response body.
type GETPointersResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *basictypes.WithPointers
}

// Close releases the response body. Always call when done.
func (r *GETPointersResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETPointersResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETPointersResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETPointersResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETPointersResponse) StatusOk() (*basictypes.WithPointers, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(basictypes.WithPointers)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// POSTPrimitivesResponse is the response for the POSTPrimitives operation.
// Call Close() when done to release the response body.
type POSTPrimitivesResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status201 *basictypes.SimplePrimitives
}

// Close releases the response body. Always call when done.
func (r *POSTPrimitivesResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *POSTPrimitivesResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *POSTPrimitivesResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *POSTPrimitivesResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusCreated returns the unmarshaled response body for status 201.
func (r *POSTPrimitivesResponse) StatusCreated() (*basictypes.SimplePrimitives, error) {
	if r.status201 != nil {
		return r.status201, nil
	}
	if r.StatusCode() != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status201 = new(basictypes.SimplePrimitives)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}
