// Code generated by clientgen. DO NOT EDIT.
// Source: 01 Basic Types Demo v1.0.0

package basictypesdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"bytes"
	"encoding/json"
	"strings"
	"github.com/arkannsk/nooa/client"
	basictypes "github.com/arkannsk/nooa/examples/models/01_basic_types"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// Client is the generated HTTP client for 01 Basic Types Demo.
type Client struct {
	BaseURL    string
	HTTPClient HTTPClient

	// Codec maps Content-Type to client.Codec for response body decoding.
	// If nil, defaults to JSON decoding for all types.
	Codec map[string]client.Codec
}

// New creates a new Client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *Client {
	var client HTTPClient
	switch v := hc.(type) {
	case nil:
		client = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		client = &stdHTTPClient{Client: v}
	case HTTPClient:
		client = v
	default:
		client = &stdHTTPClient{Client: &http.Client{}}
	}
	return &Client{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: client,
	}
}


// Create with default values
// POST /defaults


// POSTDefaultsRequest holds parameters for POSTDefaults.
type POSTDefaultsRequest struct {
	// Body is the request body.
	Body basictypes.WithDefaults
}

// POSTDefaultsResponse holds the response for POSTDefaults.
type POSTDefaultsResponse struct {
	*http.Response
	client *Client
	status201 *basictypes.WithDefaults
}

func (r *POSTDefaultsResponse) StatusCreated() (*basictypes.WithDefaults, error) {
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.status201 != nil {
		return r.status201, nil
	}
	r.status201 = new(basictypes.WithDefaults)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// POSTDefaults — Create with default values
func (c *Client) POSTDefaults(ctx context.Context, input *POSTDefaultsRequest) (*POSTDefaultsResponse, error) {

	u := c.BaseURL + "/defaults"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &POSTDefaultsResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Get nullable pointer fields
// GET /pointers


// GETPointersResponse holds the response for GETPointers.
type GETPointersResponse struct {
	*http.Response
	client *Client
	status200 *basictypes.WithPointers
}

func (r *GETPointersResponse) StatusOk() (*basictypes.WithPointers, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(basictypes.WithPointers)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETPointers — Get nullable pointer fields
func (c *Client) GETPointers(ctx context.Context) (*GETPointersResponse, error) {

	u := c.BaseURL + "/pointers"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &GETPointersResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Create with primitive types
// POST /primitives


// POSTPrimitivesRequest holds parameters for POSTPrimitives.
type POSTPrimitivesRequest struct {
	// Body is the request body.
	Body basictypes.SimplePrimitives
}

// POSTPrimitivesResponse holds the response for POSTPrimitives.
type POSTPrimitivesResponse struct {
	*http.Response
	client *Client
	status201 *basictypes.SimplePrimitives
}

func (r *POSTPrimitivesResponse) StatusCreated() (*basictypes.SimplePrimitives, error) {
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.status201 != nil {
		return r.status201, nil
	}
	r.status201 = new(basictypes.SimplePrimitives)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// POSTPrimitives — Create with primitive types
func (c *Client) POSTPrimitives(ctx context.Context, input *POSTPrimitivesRequest) (*POSTPrimitivesResponse, error) {

	u := c.BaseURL + "/primitives"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &POSTPrimitivesResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



