// Code generated by elval-gen. DO NOT EDIT.
// Source: mixed.go

package mixed

import (
	errs "github.com/arkannsk/elval/pkg/errs"
	oa "github.com/arkannsk/elval/pkg/openapi"
	"net/http"
	"strconv"
)

func (v *MegaStruct) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 10),
		Required:   make([]string, 0, 10),
		Ref:        v.GlobalRef(),
	}
	schema.Deps = []any{
		new(UserVariant),
		new(AdminVariant),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")
		prop.MinLength = oa.Ptr[int64](2)
		prop.MaxLength = oa.Ptr[int64](50)

		prop.Description = "User name"

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		schema.Required = append(schema.Required, "avatar")

		prop.Description = "Avatar image"

		schema.Properties["avatar"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "Raw payload"

		schema.Properties["payload"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "byte"

		prop.Description = "Base64 thumbnail"
		prop.Format = "byte"

		schema.Properties["thumbnail"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "status")

		schema.Properties["status"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](10)

		schema.Properties["tags"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/github.com/arkannsk/elval/examples/13_mixed.Address"

		schema.Properties["address"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"

		prop.Description = "Optional email"

		schema.Properties["email"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.OneOf = []*oa.Schema{
			{Ref: "#/components/schemas/github.com/arkannsk/nooa/examples/models/13_mixed.UserVariant"},
			{Ref: "#/components/schemas/github.com/arkannsk/nooa/examples/models/13_mixed.AdminVariant"},
		}

		schema.Properties["variant"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"

		schema.Properties["customid"] = prop
	}

	schema.Discriminator = &oa.Discriminator{
		PropertyName: "kind",
		Mapping: map[string]string{
			"admin": "AdminVariant",
			"user":  "UserVariant",
		},
	}

	return schema
}

func (v *MegaStruct) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/13_mixed.MegaStruct"
}

// OaParams возвращает параметры OpenAPI для этой структуры
func (v *MegaStruct) OaParams() []*oa.Parameter {
	params := []*oa.Parameter{}

	params = append(params, &oa.Parameter{
		Name:     "ID",
		In:       oa.ParamPath,
		Required: true,
		Schema:   v.getFieldSchema("ID"),
	})

	params = append(params, &oa.Parameter{
		Name:     "IncludeDeleted",
		In:       oa.ParamQuery,
		Required: false,
		Schema:   v.getFieldSchema("IncludeDeleted"),
	})

	params = append(params, &oa.Parameter{
		Name:     "APIVersion",
		In:       oa.ParamHeader,
		Required: false,
		Schema:   v.getFieldSchema("APIVersion"),
	})
	return params
}

// getFieldSchema вспомогательный метод для получения схемы конкретного поля
func (v *MegaStruct) getFieldSchema(fieldName string) *oa.Schema {
	switch fieldName {
	case "ID":

		return &oa.Schema{
			Type: "string",
		}
	case "Name":

		return &oa.Schema{
			Type: "string",
		}
	case "Avatar":

		return &oa.Schema{
			Type: "object",
		}
	case "Payload":

		return &oa.Schema{
			Type: "object",
		}
	case "Thumbnail":

		return &oa.Schema{
			Type:   "array",
			Format: "byte",

			Items: &oa.Schema{
				Type: "object",
			},
		}
	case "Status":

		return &oa.Schema{
			Type: "string",
			Enum: []any{
				"active\"",
				"\"inactive",
			},
		}
	case "Tags":

		return &oa.Schema{
			Type: "array",

			Items: &oa.Schema{
				Type: "string",
			},
		}
	case "Address":

		return &oa.Schema{
			Type: "object",
		}
	case "Email":

		return &oa.Schema{
			Type: "object",
		}
	case "Variant":

		return &oa.Schema{
			Type: "object",
		}
	case "IncludeDeleted":

		return &oa.Schema{
			Type: "boolean",
		}
	case "APIVersion":

		return &oa.Schema{
			Type: "string",
		}
	case "CustomID":

		return &oa.Schema{
			Type: "object",
		}
	default:
		return nil
	}
}

func (v *MegaStruct) ParseRequest(r *http.Request) error {
	{
		// Parameter: ID (path)
		// Parsing primitive: string
		v.ID = r.PathValue("ID")
	}
	{
		// Parameter: IncludeDeleted (query)
		// Parsing primitive: bools
		if vals := r.URL.Query()["IncludeDeleted"]; len(vals) > 0 {
			parsedBool, err := strconv.ParseBool(vals[0])
			if err != nil {
				return errs.NewParseRequestError("IncludeDeleted", vals[0], "invalid bool")
			}
			v.IncludeDeleted = parsedBool
		}
	}
	{
		// Parameter: APIVersion (header)
		// Parsing primitive: string
		v.APIVersion = r.Header.Get("APIVersion")
	}
	return nil
}

func (v *Address) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["street"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["city"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["country"] = prop
	}

	return schema
}

func (v *Address) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/13_mixed.Address"
}

func (v *UserVariant) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["kind"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["username"] = prop
	}

	return schema
}

func (v *UserVariant) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/13_mixed.UserVariant"
}

func (v *AdminVariant) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["kind"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["adminlevel"] = prop
	}

	return schema
}

func (v *AdminVariant) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/13_mixed.AdminVariant"
}
