// Code generated by clientgen. DO NOT EDIT.
// Source: 15 Response Content Demo v1.0.0

package responsecontentdemo

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"bytes"
	responsecontent "github.com/arkannsk/nooa/examples/models/15_response_content"
)

// HTTPClient is the interface that wraps the Do method.
// It is compatible with *http.Client and useful for testing.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client is the generated HTTP client for 15 Response Content Demo.
type Client struct {
	BaseURL     string
	HTTPClient  HTTPClient
	Token       string
	TokenPrefix string
}

// New creates a new Client.
func New(baseURL string, hc HTTPClient) *Client {
	if hc == nil {
		hc = &http.Client{}
	}
	return &Client{
		BaseURL:     strings.TrimRight(baseURL, "/"),
		HTTPClient:  hc,
		TokenPrefix: "Bearer",
	}
}


// Create user
// POST /create


// POSTCreateRequest holds parameters for POSTCreate.
type POSTCreateRequest struct {
	// Body is the request body.
	Body responsecontent.CreateUserResponse
}

// POSTCreateResponse holds the response for POSTCreate.
type POSTCreateResponse struct {
	// Status 200 — response_content.CreateUserResponse
	Status200 responsecontent.CreateUserResponse
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// POSTCreate — Create user
func (c *Client) POSTCreate(ctx context.Context, input *POSTCreateRequest) (*POSTCreateResponse, error) {

	u := c.BaseURL + "/create"

	var body io.Reader

	if input != nil {
		b, err := json.Marshal(input.Body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &POSTCreateResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Error response
// POST /error


// POSTErrorResponse holds the response for POSTError.
type POSTErrorResponse struct {
	// Status 200 — response_content.ErrorResponse
	Status200 responsecontent.ErrorResponse
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// POSTError — Error response
func (c *Client) POSTError(ctx context.Context) (*POSTErrorResponse, error) {

	u := c.BaseURL + "/error"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &POSTErrorResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Multiple response codes
// GET /multi


// GETMultiResponse holds the response for GETMulti.
type GETMultiResponse struct {
	// Status 200 — response_content.MultipleResponses
	Status200 responsecontent.MultipleResponses
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETMulti — Multiple response codes
func (c *Client) GETMulti(ctx context.Context) (*GETMultiResponse, error) {

	u := c.BaseURL + "/multi"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETMultiResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// No response annotation
// GET /no-content


// GETNocontentResponse holds the response for GETNocontent.
type GETNocontentResponse struct {
	// Status 200 — response_content.NoContentType
	Status200 responsecontent.NoContentType
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETNocontent — No response annotation
func (c *Client) GETNocontent(ctx context.Context) (*GETNocontentResponse, error) {

	u := c.BaseURL + "/no-content"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETNocontentResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// No media types
// GET /no-media


// GETNomediaResponse holds the response for GETNomedia.
type GETNomediaResponse struct {
	// Status 200 — response_content.NoMediaTypes
	Status200 responsecontent.NoMediaTypes
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETNomedia — No media types
func (c *Client) GETNomedia(ctx context.Context) (*GETNomediaResponse, error) {

	u := c.BaseURL + "/no-media"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETNomediaResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Get user response
// GET /user


// GETUserResponse holds the response for GETUser.
type GETUserResponse struct {
	// Status 200 — response_content.UserResponse
	Status200 responsecontent.UserResponse
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETUser — Get user response
func (c *Client) GETUser(ctx context.Context) (*GETUserResponse, error) {

	u := c.BaseURL + "/user"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETUserResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



