// Code generated by clientgen. DO NOT EDIT.
// Source: 09 Ignore Demo v1.0.0

package ignoredemo

import (
	"context"
	"net/http"
	"strings"
	"bytes"
	"fmt"
	"io"
	"sync"
	nooaclient "github.com/arkannsk/nooa/client"
	ignore "github.com/arkannsk/nooa/examples/models/09_ignore"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// httpc is the internal HTTP client shared by all tag adapters.
type httpc struct {
	BaseURL    string
	HTTPClient HTTPClient
	Codec      map[string]nooaclient.Codec
}

func newHTTPC(baseURL string, hc any) *httpc {
	var httpClient HTTPClient
	switch v := hc.(type) {
	case nil:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		httpClient = &stdHTTPClient{Client: v}
	case HTTPClient:
		httpClient = v
	default:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	}
	return &httpc{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: httpClient,
	}
}
// V1 is the HTTP client for 09 Ignore Demo.
type V1 struct {
	base *httpc
}

// New creates a new V1 client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *V1 {
	return &V1{base: newHTTPC(baseURL, hc)}
}

// Struct with an ignored field
// GET /ignored-field
func (c *V1) GETIgnoredfield(ctx context.Context, input *ignore.WithIgnoredField) (*GETIgnoredfieldResponse, error) {

	path := "/ignored-field"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETIgnoredfieldResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// Struct with all fields ignored
// GET /only-ignored
func (c *V1) GETOnlyignored(ctx context.Context, input *ignore.OnlyIgnoredFields) (*GETOnlyignoredResponse, error) {

	path := "/only-ignored"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETOnlyignoredResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// Field overrides ignored type
// GET /override
func (c *V1) GETOverride(ctx context.Context, input *ignore.WithOverride) (*GETOverrideResponse, error) {

	path := "/override"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETOverrideResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// GETIgnoredfieldResponse is the response for the GETIgnoredfield operation.
// Call Close() when done to release the response body.
type GETIgnoredfieldResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *ignore.WithIgnoredField
}

// Close releases the response body. Always call when done.
func (r *GETIgnoredfieldResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETIgnoredfieldResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETIgnoredfieldResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETIgnoredfieldResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETIgnoredfieldResponse) StatusOk() (*ignore.WithIgnoredField, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(ignore.WithIgnoredField)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETOnlyignoredResponse is the response for the GETOnlyignored operation.
// Call Close() when done to release the response body.
type GETOnlyignoredResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *ignore.OnlyIgnoredFields
}

// Close releases the response body. Always call when done.
func (r *GETOnlyignoredResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETOnlyignoredResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETOnlyignoredResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETOnlyignoredResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETOnlyignoredResponse) StatusOk() (*ignore.OnlyIgnoredFields, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(ignore.OnlyIgnoredFields)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETOverrideResponse is the response for the GETOverride operation.
// Call Close() when done to release the response body.
type GETOverrideResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *ignore.WithOverride
}

// Close releases the response body. Always call when done.
func (r *GETOverrideResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETOverrideResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETOverrideResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETOverrideResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETOverrideResponse) StatusOk() (*ignore.WithOverride, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(ignore.WithOverride)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
