// Code generated by elval-gen. DO NOT EDIT.
// Source: response.go

package response_content

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *UserResponse) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Standard user response"
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Description = "User ID"

		schema.Properties["id"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "User name"

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "User email"

		schema.Properties["email"] = prop
	}

	return schema
}

func (v *UserResponse) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/15_response_content.UserResponse"
}
func (v *UserResponse) OaResponses() map[int]*oa.Response {
	responses := make(map[int]*oa.Response)
	responses[200] = &oa.Response{
		Description: v.GlobalRef(),
		Content: map[string]*oa.MediaType{
			"application/json": {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
			"application/xml":  {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
		},
	}
	return responses
}

func (v *ErrorResponse) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Error response"
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Description = "Error code"

		schema.Properties["code"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Error message"

		schema.Properties["message"] = prop
	}

	return schema
}

func (v *ErrorResponse) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/15_response_content.ErrorResponse"
}
func (v *ErrorResponse) OaResponses() map[int]*oa.Response {
	responses := make(map[int]*oa.Response)
	responses[400] = &oa.Response{
		Description: v.GlobalRef(),
		Content: map[string]*oa.MediaType{
			"application/json": {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
		},
	}
	return responses
}

func (v *CreateUserResponse) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "User creation response"
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Description = "Created user ID"

		schema.Properties["id"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "User name"

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Creation timestamp"

		schema.Properties["created_at"] = prop
	}

	return schema
}

func (v *CreateUserResponse) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/15_response_content.CreateUserResponse"
}
func (v *CreateUserResponse) OaResponses() map[int]*oa.Response {
	responses := make(map[int]*oa.Response)
	responses[200] = &oa.Response{
		Description: v.GlobalRef(),
		Content: map[string]*oa.MediaType{
			"application/json": {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
			"application/xml":  {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
		},
	}
	responses[201] = &oa.Response{
		Description: v.GlobalRef(),
		Content: map[string]*oa.MediaType{
			"application/json": {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
		},
	}
	return responses
}

func (v *NoContentType) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Struct without response annotation"
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["value"] = prop
	}

	return schema
}

func (v *NoContentType) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/15_response_content.NoContentType"
}

func (v *NoMediaTypes) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 0),
		Required:   make([]string, 0, 0),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Response without media types"

	return schema
}

func (v *NoMediaTypes) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/15_response_content.NoMediaTypes"
}
func (v *NoMediaTypes) OaResponses() map[int]*oa.Response {
	responses := make(map[int]*oa.Response)
	responses[204] = &oa.Response{
		Description: v.GlobalRef(),
		Content:     map[string]*oa.MediaType{},
	}
	return responses
}

func (v *MultipleResponses) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Multiple response codes"
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Data payload"

		schema.Properties["data"] = prop
	}

	return schema
}

func (v *MultipleResponses) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/15_response_content.MultipleResponses"
}
func (v *MultipleResponses) OaResponses() map[int]*oa.Response {
	responses := make(map[int]*oa.Response)
	responses[200] = &oa.Response{
		Description: v.GlobalRef(),
		Content: map[string]*oa.MediaType{
			"application/json": {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
		},
	}
	responses[401] = &oa.Response{
		Description: v.GlobalRef(),
		Content: map[string]*oa.MediaType{
			"application/json": {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
		},
	}
	responses[500] = &oa.Response{
		Description: v.GlobalRef(),
		Content: map[string]*oa.MediaType{
			"application/json": {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
		},
	}
	return responses
}
