// Code generated by elval-gen. DO NOT EDIT.
// Source: rewrite.go

package rewrite

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *WithRewriteType) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"

		prop.Description = "JSON payload documented as string"

		schema.Properties["rawjson"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "integer"

		prop.Description = "Custom ID type documented as integer"

		schema.Properties["customid"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Description = "Custom slice documented as array"

		schema.Properties["customlist"] = prop
	}

	return schema
}

func (v *WithRewriteType) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.WithRewriteType"
}

func (v *WithRewriteRef) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/CommonMetadata"

		prop.Description = "Reference to local stub"

		schema.Properties["meta"] = prop
	}

	return schema
}

func (v *WithRewriteRef) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.WithRewriteRef"
}

func (v *CommonMetadata) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Creation timestamp"

		schema.Properties["createdat"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Last update timestamp"

		schema.Properties["updatedat"] = prop
	}

	return schema
}

func (v *CommonMetadata) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.CommonMetadata"
}

func (v *CreateLocationRequest) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/FeatureDocs"

		schema.Properties["feature"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "User ID"

		schema.Properties["userid"] = prop
	}

	return schema
}

func (v *CreateLocationRequest) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.CreateLocationRequest"
}

func (v *FeatureDocs) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Must be 'Feature'"

		schema.Properties["type"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/GeometryDocs"

		prop.Description = "GeoJSON geometry"

		schema.Properties["geometry"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "object"

		prop.Description = "Feature properties (arbitrary JSON object)"

		schema.Properties["properties"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "number"

		prop.Description = "Feature bounding box"

		schema.Properties["bbox"] = prop
	}

	return schema
}

func (v *FeatureDocs) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.FeatureDocs"
}

func (v *GeometryDocs) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Geometry type"

		schema.Properties["type"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "object"

		prop.Description = "Geometry coordinates"

		schema.Properties["coordinates"] = prop
	}

	return schema
}

func (v *GeometryDocs) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.GeometryDocs"
}

func (v *CreateLocationWithPoint) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/PointDocs"

		schema.Properties["location"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Name of the location"

		schema.Properties["name"] = prop
	}

	return schema
}

func (v *CreateLocationWithPoint) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.CreateLocationWithPoint"
}

func (v *PointDocs) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "number"

		prop.Description = "Longitude"

		schema.Properties["longitude"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "number"

		prop.Description = "Latitude"

		schema.Properties["latitude"] = prop
	}

	return schema
}

func (v *PointDocs) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.PointDocs"
}
