// Code generated by elval-gen. DO NOT EDIT.
// Source: rewrite.go

package rewrite

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *WithRewriteType) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"

		prop.Description = "JSON payload documented as string"

		schema.Properties["rawjson"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "integer"

		prop.Description = "Custom ID type documented as integer"

		schema.Properties["customid"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Description = "Custom slice documented as array"

		schema.Properties["customlist"] = prop
	}

	return schema
}

func (v *WithRewriteType) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.WithRewriteType"
}

func (v *WithRewriteRef) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/github.com/arkannsk/elval/examples/07_rewrite.ExternalSchema"

		prop.Description = "Reference to external schema"

		schema.Properties["external"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/CommonMetadata"

		prop.Description = "Reference to local stub"

		schema.Properties["meta"] = prop
	}

	return schema
}

func (v *WithRewriteRef) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.WithRewriteRef"
}

func (v *ExternalType) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["field"] = prop
	}

	return schema
}

func (v *ExternalType) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.ExternalType"
}

func (v *CommonMetadata) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Creation timestamp"

		schema.Properties["createdat"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Last update timestamp"

		schema.Properties["updatedat"] = prop
	}

	return schema
}

func (v *CommonMetadata) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/07_rewrite.CommonMetadata"
}
