// Code generated by clientgen. DO NOT EDIT.
// Source: 15 Response Content Demo v1.0.0

package responsecontentdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	nooaclient "github.com/arkannsk/nooa/client"
	responsecontent "github.com/arkannsk/nooa/examples/models/15_response_content"
)

// MultiStatusClient groups the MultiStatus operations.
type MultiStatusClient interface {
	GETMulti(ctx context.Context, opts ...nooaclient.RequestOption) (*GETMultiResponse, error)
}

// multiStatusAdapter implements MultiStatusClient.
type multiStatusAdapter struct {
	httpc *httpc
}

// Multiple response codes
// GET /multi
func (t *multiStatusAdapter) GETMulti(ctx context.Context, opts ...nooaclient.RequestOption) (*GETMultiResponse, error) {

	path := "/multi"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETMultiResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      t.httpc,
	}, nil
}

// GETMultiResponse is the response for the GETMulti operation.
type GETMultiResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *responsecontent.MultipleResponses
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETMultiResponse) StatusOk() (*responsecontent.MultipleResponses, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(responsecontent.MultipleResponses)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
