// Code generated by clientgen. DO NOT EDIT.
// Source: 15 Response Content Demo v1.0.0

package responsecontentdemo

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"sync"
	"encoding/json"
	nooaclient "github.com/arkannsk/nooa/client"
	responsecontent "github.com/arkannsk/nooa/examples/models/15_response_content"
)

// ResponsesClient groups the Responses operations.
type ResponsesClient interface {
	POSTCreate(ctx context.Context, input *responsecontent.CreateUserResponse) (*POSTCreateResponse, error)
	POSTError(ctx context.Context, opts ...nooaclient.RequestOption) (*POSTErrorResponse, error)
	GETNocontent(ctx context.Context, opts ...nooaclient.RequestOption) (*GETNocontentResponse, error)
	GETNomedia(ctx context.Context, opts ...nooaclient.RequestOption) (*GETNomediaResponse, error)
	GETUser(ctx context.Context, opts ...nooaclient.RequestOption) (*GETUserResponse, error)
}

// responsesAdapter implements ResponsesClient.
type responsesAdapter struct {
	httpc *httpc
}

// Create user
// POST /create
func (t *responsesAdapter) POSTCreate(ctx context.Context, input *responsecontent.CreateUserResponse) (*POSTCreateResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/create"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &POSTCreateResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// Error response
// POST /error
func (t *responsesAdapter) POSTError(ctx context.Context, opts ...nooaclient.RequestOption) (*POSTErrorResponse, error) {

	path := "/error"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &POSTErrorResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// No response annotation
// GET /no-content
func (t *responsesAdapter) GETNocontent(ctx context.Context, opts ...nooaclient.RequestOption) (*GETNocontentResponse, error) {

	path := "/no-content"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETNocontentResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// No media types
// GET /no-media
func (t *responsesAdapter) GETNomedia(ctx context.Context, opts ...nooaclient.RequestOption) (*GETNomediaResponse, error) {

	path := "/no-media"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETNomediaResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// Get user response
// GET /user
func (t *responsesAdapter) GETUser(ctx context.Context, opts ...nooaclient.RequestOption) (*GETUserResponse, error) {

	path := "/user"

	requestURL := t.httpc.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := t.httpc.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETUserResponse{
		resp:  httpResp,
		codec: t.httpc.Codec,
	}, nil
}

// POSTCreateResponse is the response for the POSTCreate operation.
// Call Close() when done to release the response body.
type POSTCreateResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status201 *responsecontent.CreateUserResponse
}

// Close releases the response body. Always call when done.
func (r *POSTCreateResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *POSTCreateResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *POSTCreateResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *POSTCreateResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusCreated returns the unmarshaled response body for status 201.
func (r *POSTCreateResponse) StatusCreated() (*responsecontent.CreateUserResponse, error) {
	if r.status201 != nil {
		return r.status201, nil
	}
	if r.StatusCode() != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status201 = new(responsecontent.CreateUserResponse)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// POSTErrorResponse is the response for the POSTError operation.
// Call Close() when done to release the response body.
type POSTErrorResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *responsecontent.ErrorResponse
}

// Close releases the response body. Always call when done.
func (r *POSTErrorResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *POSTErrorResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *POSTErrorResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *POSTErrorResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *POSTErrorResponse) StatusOk() (*responsecontent.ErrorResponse, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(responsecontent.ErrorResponse)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETNocontentResponse is the response for the GETNocontent operation.
// Call Close() when done to release the response body.
type GETNocontentResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *responsecontent.NoContentType
}

// Close releases the response body. Always call when done.
func (r *GETNocontentResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETNocontentResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETNocontentResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETNocontentResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETNocontentResponse) StatusOk() (*responsecontent.NoContentType, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(responsecontent.NoContentType)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETNomediaResponse is the response for the GETNomedia operation.
// Call Close() when done to release the response body.
type GETNomediaResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status204 *responsecontent.NoMediaTypes
}

// Close releases the response body. Always call when done.
func (r *GETNomediaResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETNomediaResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETNomediaResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETNomediaResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusNoContent returns the unmarshaled response body for status 204.
func (r *GETNomediaResponse) StatusNoContent() (*responsecontent.NoMediaTypes, error) {
	if r.status204 != nil {
		return r.status204, nil
	}
	if r.StatusCode() != 204 {
		return nil, fmt.Errorf("expected status 204, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status204 = new(responsecontent.NoMediaTypes)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status204); err != nil {
		return nil, err
	}
	return r.status204, nil
}

// GETUserResponse is the response for the GETUser operation.
// Call Close() when done to release the response body.
type GETUserResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *responsecontent.UserResponse
}

// Close releases the response body. Always call when done.
func (r *GETUserResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETUserResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETUserResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETUserResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETUserResponse) StatusOk() (*responsecontent.UserResponse, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(responsecontent.UserResponse)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
