// Code generated by clientgen. DO NOT EDIT.
// Source: 14 Struct Tags Demo v1.0.0

package structtagsdemo

import (
	"context"
	"net/http"
	"strings"
	"fmt"
	"io"
	"bytes"
	"encoding/json"
	nooaclient "github.com/arkannsk/nooa/client"
	structtags "github.com/arkannsk/nooa/examples/models/14_struct_tags"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// httpc is the internal HTTP client shared by all tag adapters.
type httpc struct {
	BaseURL    string
	HTTPClient HTTPClient
	Codec      map[string]nooaclient.Codec
}

func newHTTPC(baseURL string, hc any) *httpc {
	var httpClient HTTPClient
	switch v := hc.(type) {
	case nil:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		httpClient = &stdHTTPClient{Client: v}
	case HTTPClient:
		httpClient = v
	default:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	}
	return &httpc{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: httpClient,
	}
}
// V1 is the HTTP client for 14 Struct Tags Demo.
type V1 struct {
	base *httpc
}

// New creates a new V1 client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *V1 {
	return &V1{base: newHTTPC(baseURL, hc)}
}

// Handle JSON tags
// POST /json
func (c *V1) POSTJson(ctx context.Context, input *structtags.JsonTagModel) (*POSTJsonResponse, error) {
	var body io.Reader
	if input != nil {
		b, err := json.Marshal(input)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		body = bytes.NewReader(b)
	}

	path := "/json"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &POSTJsonResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Handle mixed tags
// GET /mixed
func (c *V1) GETMixed(ctx context.Context, input *structtags.MixedTagsModel) (*GETMixedResponse, error) {

	path := "/mixed"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETMixedResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Handle XML tags
// GET /xml
func (c *V1) GETXml(ctx context.Context, input *structtags.XmlTagModel) (*GETXmlResponse, error) {

	path := "/xml"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETXmlResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Handle YAML tags
// GET /yaml
func (c *V1) GETYaml(ctx context.Context, input *structtags.YamlTagModel) (*GETYamlResponse, error) {

	path := "/yaml"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETYamlResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// POSTJsonResponse is the response for the POSTJson operation.
type POSTJsonResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *structtags.JsonTagModel
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *POSTJsonResponse) StatusOk() (*structtags.JsonTagModel, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(structtags.JsonTagModel)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETMixedResponse is the response for the GETMixed operation.
type GETMixedResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *structtags.MixedTagsModel
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETMixedResponse) StatusOk() (*structtags.MixedTagsModel, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(structtags.MixedTagsModel)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETXmlResponse is the response for the GETXml operation.
type GETXmlResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *structtags.XmlTagModel
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETXmlResponse) StatusOk() (*structtags.XmlTagModel, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(structtags.XmlTagModel)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETYamlResponse is the response for the GETYaml operation.
type GETYamlResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *structtags.YamlTagModel
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETYamlResponse) StatusOk() (*structtags.YamlTagModel, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(structtags.YamlTagModel)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
