// Code generated by clientgen. DO NOT EDIT.
// Source: 02 Files & Streams Demo v1.0.0

package filesstreamsdemo

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"github.com/arkannsk/nooa/client"
	filesstream "github.com/arkannsk/nooa/examples/models/02_files_stream"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// Client is the generated HTTP client for 02 Files & Streams Demo.
type Client struct {
	BaseURL    string
	HTTPClient HTTPClient

	// Codec maps Content-Type to client.Codec for response body decoding.
	// If nil, defaults to JSON decoding for all types.
	Codec map[string]client.Codec
}

// New creates a new Client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *Client {
	var client HTTPClient
	switch v := hc.(type) {
	case nil:
		client = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		client = &stdHTTPClient{Client: v}
	case HTTPClient:
		client = v
	default:
		client = &stdHTTPClient{Client: &http.Client{}}
	}
	return &Client{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: client,
	}
}

// RequestOption modifies an HTTP request before it is sent.
// Use WithBody, WithQuery, WithHeader, WithPath to configure a request.
type RequestOption func(*http.Request)

// WithBody sets the request body (JSON-encoded).
func WithBody(v any) RequestOption {
	return func(r *http.Request) {
		b, err := json.Marshal(v)
		if err != nil {
			return
		}
		r.Body = io.NopCloser(bytes.NewReader(b))
		r.Header.Set("Content-Type", "application/json")
	}
}

// WithQuery adds a query parameter.
func WithQuery(key string, value any) RequestOption {
	return func(r *http.Request) {
		q := r.URL.Query()
		q.Set(key, fmt.Sprintf("%v", value))
		r.URL.RawQuery = q.Encode()
	}
}

// WithHeader sets a request header.
func WithHeader(key, value string) RequestOption {
	return func(r *http.Request) {
		r.Header.Set(key, value)
	}
}

// WithPath substitutes a path placeholder {key} with the given value.
func WithPath(key string, value any) RequestOption {
	return func(r *http.Request) {
		r.URL.Path = strings.ReplaceAll(r.URL.Path, "{"+key+"}", fmt.Sprintf("%v", value))
	}
}


// Upload with custom annotated types
// POST /custom


// POSTCustomResponse holds the response for POSTCustom.
type POSTCustomResponse struct {
	*http.Response
	client *Client
	status201 *filesstream.CustomWithAnnotations
}

func (r *POSTCustomResponse) StatusCreated() (*filesstream.CustomWithAnnotations, error) {
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.status201 != nil {
		return r.status201, nil
	}
	r.status201 = new(filesstream.CustomWithAnnotations)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// POSTCustom — Upload with custom annotated types
// POST /custom
func (c *Client) POSTCustom(ctx context.Context, input *filesstream.CustomWithAnnotations) (*POSTCustomResponse, error) {

	u := c.BaseURL + "/custom"



	var body io.Reader
	b, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("marshal request body: %w", err)
	}
	body = bytes.NewReader(b)

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		rb, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("request failed: status %d, body: %s", resp.StatusCode, string(rb))
	}
	return &POSTCustomResponse{
		Response: resp,
		client:   c,
	}, nil
}



// Upload with mixed request
// POST /mixed


// POSTMixedResponse holds the response for POSTMixed.
type POSTMixedResponse struct {
	*http.Response
	client *Client
	status201 *filesstream.MixedRequest
}

func (r *POSTMixedResponse) StatusCreated() (*filesstream.MixedRequest, error) {
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.status201 != nil {
		return r.status201, nil
	}
	r.status201 = new(filesstream.MixedRequest)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// POSTMixed — Upload with mixed request
// POST /mixed
func (c *Client) POSTMixed(ctx context.Context, input *filesstream.MixedRequest) (*POSTMixedResponse, error) {

	u := c.BaseURL + "/mixed"



	var body io.Reader
	b, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("marshal request body: %w", err)
	}
	body = bytes.NewReader(b)

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		rb, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("request failed: status %d, body: %s", resp.StatusCode, string(rb))
	}
	return &POSTMixedResponse{
		Response: resp,
		client:   c,
	}, nil
}



// Upload with standard file types
// POST /standard


// POSTStandardResponse holds the response for POSTStandard.
type POSTStandardResponse struct {
	*http.Response
	client *Client
	status201 *filesstream.StandardFileTypes
}

func (r *POSTStandardResponse) StatusCreated() (*filesstream.StandardFileTypes, error) {
	if r.StatusCode != 201 {
		return nil, fmt.Errorf("expected status 201, got %d", r.StatusCode)
	}
	if r.status201 != nil {
		return r.status201, nil
	}
	r.status201 = new(filesstream.StandardFileTypes)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status201); err != nil {
		return nil, err
	}
	return r.status201, nil
}

// POSTStandard — Upload with standard file types
// POST /standard
func (c *Client) POSTStandard(ctx context.Context, input *filesstream.StandardFileTypes) (*POSTStandardResponse, error) {

	u := c.BaseURL + "/standard"



	var body io.Reader
	b, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("marshal request body: %w", err)
	}
	body = bytes.NewReader(b)

	httpReq, err := http.NewRequestWithContext(ctx, "POST", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		rb, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("request failed: status %d, body: %s", resp.StatusCode, string(rb))
	}
	return &POSTStandardResponse{
		Response: resp,
		client:   c,
	}, nil
}



