// Code generated by clientgen. DO NOT EDIT.
// Source: 04 Slice/Map Demo v1.0.0

package slicemapdemo

import (
	"context"
	"net/http"
	"strings"
	"fmt"
	"io"
	nooaclient "github.com/arkannsk/nooa/client"
	slicemaps "github.com/arkannsk/nooa/examples/models/04_slice_maps"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// httpc is the internal HTTP client shared by all tag adapters.
type httpc struct {
	BaseURL    string
	HTTPClient HTTPClient
	Codec      map[string]nooaclient.Codec
}

func newHTTPC(baseURL string, hc any) *httpc {
	var httpClient HTTPClient
	switch v := hc.(type) {
	case nil:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		httpClient = &stdHTTPClient{Client: v}
	case HTTPClient:
		httpClient = v
	default:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	}
	return &httpc{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: httpClient,
	}
}
// V1 is the HTTP client for 04 Slice/Map Demo.
type V1 struct {
	base *httpc
}

// New creates a new V1 client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *V1 {
	return &V1{base: newHTTPC(baseURL, hc)}
}

// Get fixed arrays
// GET /arrays
func (c *V1) GETArrays(ctx context.Context, input *slicemaps.ArrayFixed) (*GETArraysResponse, error) {

	path := "/arrays"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETArraysResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Get map variations
// GET /maps
func (c *V1) GETMaps(ctx context.Context, input *slicemaps.MapVariations) (*GETMapsResponse, error) {

	path := "/maps"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETMapsResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// Get slice variations
// GET /slices
func (c *V1) GETSlices(ctx context.Context, input *slicemaps.SliceVariations) (*GETSlicesResponse, error) {

	path := "/slices"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response body: %w", err)
	}
	return &GETSlicesResponse{
		StatusCode: httpResp.StatusCode,
		RawBody:    rawBody,
		httpc:      c.base,
	}, nil
}

// GETArraysResponse is the response for the GETArrays operation.
type GETArraysResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *slicemaps.ArrayFixed
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETArraysResponse) StatusOk() (*slicemaps.ArrayFixed, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(slicemaps.ArrayFixed)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETMapsResponse is the response for the GETMaps operation.
type GETMapsResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *slicemaps.MapVariations
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETMapsResponse) StatusOk() (*slicemaps.MapVariations, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(slicemaps.MapVariations)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETSlicesResponse is the response for the GETSlices operation.
type GETSlicesResponse struct {
	StatusCode int
	RawBody    []byte
	httpc      *httpc
	status200 *slicemaps.SliceVariations
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETSlicesResponse) StatusOk() (*slicemaps.SliceVariations, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.RawBody == nil || len(r.RawBody) == 0 {
		return nil, fmt.Errorf("empty response body")
	}
	r.status200 = new(slicemaps.SliceVariations)
	if err := nooaclient.UnmarshalBody(r.RawBody, "", r.httpc.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
