// Code generated by clientgen. DO NOT EDIT.
// Source: 04 Slice/Map Demo v1.0.0

package slicemapdemo

import (
	"context"
	"net/http"
	"strings"
	"fmt"
	"io"
	"sync"
	nooaclient "github.com/arkannsk/nooa/client"
	slicemaps "github.com/arkannsk/nooa/examples/models/04_slice_maps"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// httpc is the internal HTTP client shared by all tag adapters.
type httpc struct {
	BaseURL    string
	HTTPClient HTTPClient
	Codec      map[string]nooaclient.Codec
}

func newHTTPC(baseURL string, hc any) *httpc {
	var httpClient HTTPClient
	switch v := hc.(type) {
	case nil:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		httpClient = &stdHTTPClient{Client: v}
	case HTTPClient:
		httpClient = v
	default:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	}
	return &httpc{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: httpClient,
	}
}
// V1 is the HTTP client for 04 Slice/Map Demo.
type V1 struct {
	base *httpc
}

// New creates a new V1 client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *V1 {
	return &V1{base: newHTTPC(baseURL, hc)}
}

// Get fixed arrays
// GET /arrays
func (c *V1) GETArrays(ctx context.Context, input *slicemaps.ArrayFixed) (*GETArraysResponse, error) {

	path := "/arrays"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETArraysResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// Get map variations
// GET /maps
func (c *V1) GETMaps(ctx context.Context, input *slicemaps.MapVariations) (*GETMapsResponse, error) {

	path := "/maps"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETMapsResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// Get slice variations
// GET /slices
func (c *V1) GETSlices(ctx context.Context, input *slicemaps.SliceVariations) (*GETSlicesResponse, error) {

	path := "/slices"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETSlicesResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// GETArraysResponse is the response for the GETArrays operation.
// Call Close() when done to release the response body.
type GETArraysResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *slicemaps.ArrayFixed
}

// Close releases the response body. Always call when done.
func (r *GETArraysResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// If the body was cached (via StatusOk or a prior read), each call
// returns a reset reader so the body can be read multiple times.
func (r *GETArraysResponse) Body() io.ReadCloser {
	if r.resp == nil {
		return nil
	}
	if seeker, ok := r.resp.Body.(io.Seeker); ok {
		seeker.Seek(0, io.SeekStart)
	}
	return r.resp.Body
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It streams directly from resp.Body without caching, so the body is consumed.
// Do not call StatusOk() or Body() after Stream() — the body will be exhausted.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *GETArraysResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if r.resp == nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// (bytes.Reader wrapped as io.ReadCloser) so subsequent reads can reuse the data.
func (r *GETArraysResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = nooaclient.NewCachedBodyReader(data)
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETArraysResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETArraysResponse) StatusOk() (*slicemaps.ArrayFixed, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(slicemaps.ArrayFixed)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETMapsResponse is the response for the GETMaps operation.
// Call Close() when done to release the response body.
type GETMapsResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *slicemaps.MapVariations
}

// Close releases the response body. Always call when done.
func (r *GETMapsResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// If the body was cached (via StatusOk or a prior read), each call
// returns a reset reader so the body can be read multiple times.
func (r *GETMapsResponse) Body() io.ReadCloser {
	if r.resp == nil {
		return nil
	}
	if seeker, ok := r.resp.Body.(io.Seeker); ok {
		seeker.Seek(0, io.SeekStart)
	}
	return r.resp.Body
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It streams directly from resp.Body without caching, so the body is consumed.
// Do not call StatusOk() or Body() after Stream() — the body will be exhausted.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *GETMapsResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if r.resp == nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// (bytes.Reader wrapped as io.ReadCloser) so subsequent reads can reuse the data.
func (r *GETMapsResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = nooaclient.NewCachedBodyReader(data)
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETMapsResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETMapsResponse) StatusOk() (*slicemaps.MapVariations, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(slicemaps.MapVariations)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETSlicesResponse is the response for the GETSlices operation.
// Call Close() when done to release the response body.
type GETSlicesResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *slicemaps.SliceVariations
}

// Close releases the response body. Always call when done.
func (r *GETSlicesResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// If the body was cached (via StatusOk or a prior read), each call
// returns a reset reader so the body can be read multiple times.
func (r *GETSlicesResponse) Body() io.ReadCloser {
	if r.resp == nil {
		return nil
	}
	if seeker, ok := r.resp.Body.(io.Seeker); ok {
		seeker.Seek(0, io.SeekStart)
	}
	return r.resp.Body
}

// Stream returns a nooaclient.StreamReader for buffered streaming of the response body.
// It streams directly from resp.Body without caching, so the body is consumed.
// Do not call StatusOk() or Body() after Stream() — the body will be exhausted.
// Use StreamOption (WithBufferSize, WithProgress) to configure the stream.
func (r *GETSlicesResponse) Stream(opts ...nooaclient.StreamOption) *nooaclient.StreamReader {
	if r.resp == nil {
		return nil
	}
	opts = append(opts, nooaclient.WithTotal(r.resp.ContentLength))
	return nooaclient.NewStreamReader(r.resp.Body, opts...)
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// (bytes.Reader wrapped as io.ReadCloser) so subsequent reads can reuse the data.
func (r *GETSlicesResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = nooaclient.NewCachedBodyReader(data)
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETSlicesResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETSlicesResponse) StatusOk() (*slicemaps.SliceVariations, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(slicemaps.SliceVariations)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
