// Code generated by elval-gen. DO NOT EDIT.
// Source: ignore.go

package ignore

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *WithIgnoredField) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Struct with ignored field"
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Public field"

		schema.Properties["public"] = prop
	}

	return schema
}

func (v *WithIgnoredField) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/09_ignore.WithIgnoredField"
}

func (v *WithOverride) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Field overrides ignored type"
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "This field is included despite type being @oa:ignore"

		schema.Properties["file"] = prop
	}

	return schema
}

func (v *WithOverride) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/09_ignore.WithOverride"
}

func (v *OnlyIgnoredFields) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 0),
		Required:   make([]string, 0, 0),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Struct with all fields ignored"

	return schema
}

func (v *OnlyIgnoredFields) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/09_ignore.OnlyIgnoredFields"
}
