// Code generated by clientgen. DO NOT EDIT.
// Source: 03 Nested Demo v1.0.0

package nesteddemo

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"github.com/arkannsk/nooa/client"
	nested "github.com/arkannsk/nooa/examples/models/03_nested"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// Client is the generated HTTP client for 03 Nested Demo.
type Client struct {
	BaseURL    string
	HTTPClient HTTPClient

	// Codec maps Content-Type to client.Codec for response body decoding.
	// If nil, defaults to JSON decoding for all types.
	Codec map[string]client.Codec
}

// New creates a new Client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *Client {
	var client HTTPClient
	switch v := hc.(type) {
	case nil:
		client = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		client = &stdHTTPClient{Client: v}
	case HTTPClient:
		client = v
	default:
		client = &stdHTTPClient{Client: &http.Client{}}
	}
	return &Client{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: client,
	}
}

// RequestOption modifies an HTTP request before it is sent.
// Use WithBody, WithQuery, WithHeader, WithPath to configure a request.
type RequestOption func(*http.Request)

// WithBody sets the request body (JSON-encoded).
func WithBody(v any) RequestOption {
	return func(r *http.Request) {
		b, err := json.Marshal(v)
		if err != nil {
			return
		}
		r.Body = io.NopCloser(bytes.NewReader(b))
		r.Header.Set("Content-Type", "application/json")
	}
}

// WithQuery adds a query parameter.
func WithQuery(key string, value any) RequestOption {
	return func(r *http.Request) {
		q := r.URL.Query()
		q.Set(key, fmt.Sprintf("%v", value))
		r.URL.RawQuery = q.Encode()
	}
}

// WithHeader sets a request header.
func WithHeader(key, value string) RequestOption {
	return func(r *http.Request) {
		r.Header.Set(key, value)
	}
}

// WithPath substitutes a path placeholder {key} with the given value.
func WithPath(key string, value any) RequestOption {
	return func(r *http.Request) {
		r.URL.Path = strings.ReplaceAll(r.URL.Path, "{"+key+"}", fmt.Sprintf("%v", value))
	}
}


// Get nested user
// GET /user


// GETUserResponse holds the response for GETUser.
type GETUserResponse struct {
	*http.Response
	client *Client
	status200 *nested.UserWithAddress
}

func (r *GETUserResponse) StatusOk() (*nested.UserWithAddress, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(nested.UserWithAddress)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETUser — Get nested user
// GET /user
func (c *Client) GETUser(ctx context.Context, input *nested.UserWithAddress) (*GETUserResponse, error) {

	u := c.BaseURL + "/user"



	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		rb, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("request failed: status %d, body: %s", resp.StatusCode, string(rb))
	}
	return &GETUserResponse{
		Response: resp,
		client:   c,
	}, nil
}



