// Code generated by elval-gen. DO NOT EDIT.
// Source: validators.go

package validators

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *AllStringValidators) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 8),
		Required:   make([]string, 0, 8),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "String field with all validators"
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")

		prop.MinLength = oa.Ptr[int64](3)

		prop.MaxLength = oa.Ptr[int64](50)

		prop.Description = "Name with length constraints"

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		prop.Description = "Email field"

		schema.Properties["email"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Pattern = `^\+?[0-9]{8,15}$`
		prop.Format = "phone"

		prop.Description = "Phone field"

		schema.Properties["phone"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Pattern = `^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`
		prop.Format = "uuid"

		prop.Description = "UUID field"

		schema.Properties["id"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Pattern = "^https:/"

		prop.Description = "Custom regex pattern"

		schema.Properties["custompattern"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Must contain substring"

		schema.Properties["role"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Must start with prefix"

		schema.Properties["url"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Must end with suffix"

		schema.Properties["domain"] = prop
	}

	return schema
}

func (v *AllStringValidators) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/10_validators.AllStringValidators"
}

func (v *AllNumericValidators) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 8),
		Required:   make([]string, 0, 8),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Numeric field with all validators"
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](0)

		prop.Maximum = oa.Ptr[float64](100)

		prop.Description = "Percentage"

		schema.Properties["percent"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](0)
		prop.ExclusiveMinimum = true

		prop.Description = "Strictly positive"

		schema.Properties["positive"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](18)

		prop.Description = "Age requirement"

		schema.Properties["age"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Maximum = oa.Ptr[float64](1000)
		prop.ExclusiveMaximum = true

		prop.Description = "Less than threshold"

		schema.Properties["count"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Maximum = oa.Ptr[float64](999)

		prop.Description = "Up to limit"

		schema.Properties["limit"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "number"

		prop.Description = "Non-zero value"

		schema.Properties["amount"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Description = "Must equal specific value"

		schema.Properties["answer"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Description = "Must not equal zero"

		schema.Properties["code"] = prop
	}

	return schema
}

func (v *AllNumericValidators) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/10_validators.AllNumericValidators"
}

func (v *AllEnumAndSliceValidators) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Enum and slice validators"
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Enum = []any{"active", "inactive", "pending"}

		prop.Description = "Status from allowed list"

		schema.Properties["status"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		schema.Required = append(schema.Required, "tags")

		prop.Minimum = oa.Ptr[float64](1)

		prop.Maximum = oa.Ptr[float64](10)

		prop.Description = "Tags with constraints"

		schema.Properties["tags"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		prop.MinLength = oa.Ptr[int64](3)
		prop.MaxLength = oa.Ptr[int64](3)

		prop.Description = "Exactly 3 items"

		schema.Properties["fixedlist"] = prop
	}

	return schema
}

func (v *AllEnumAndSliceValidators) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/10_validators.AllEnumAndSliceValidators"
}

func (v *DateAndDurationValidators) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Date and duration validators"
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Date after threshold"

		schema.Properties["startdate"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Date before deadline"

		schema.Properties["enddate"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Non-zero timestamp"

		schema.Properties["timestamp"] = prop
	}

	return schema
}

func (v *DateAndDurationValidators) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/10_validators.DateAndDurationValidators"
}
