// Code generated by clientgen. DO NOT EDIT.
// Source: 11 Edge Cases Demo v1.0.0

package edgecasesdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"
	"github.com/arkannsk/nooa/client"
	edgecases "github.com/arkannsk/nooa/examples/models/11_edge_cases"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// Client is the generated HTTP client for 11 Edge Cases Demo.
type Client struct {
	BaseURL     string
	HTTPClient  HTTPClient
	Token       string
	TokenPrefix string

	// Codec maps Content-Type to client.Codec for response body decoding.
	// If nil, defaults to JSON decoding for all types.
	Codec map[string]client.Codec
}

// New creates a new Client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *Client {
	var client HTTPClient
	switch v := hc.(type) {
	case nil:
		client = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		client = &stdHTTPClient{Client: v}
	case HTTPClient:
		client = v
	default:
		client = &stdHTTPClient{Client: &http.Client{}}
	}
	return &Client{
		BaseURL:     strings.TrimRight(baseURL, "/"),
		HTTPClient:  client,
		TokenPrefix: "Bearer",
	}
}


// Circular reference
// GET /circular


// GETCircularResponse holds the response for GETCircular.
type GETCircularResponse struct {
	*http.Response
	client *Client
	status200 *edgecases.CircularRefA
}

func (r *GETCircularResponse) StatusOk() (*edgecases.CircularRefA, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(edgecases.CircularRefA)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETCircular — Circular reference
func (c *Client) GETCircular(ctx context.Context) (*GETCircularResponse, error) {

	u := c.BaseURL + "/circular"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &GETCircularResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Empty struct
// GET /empty


// GETEmptyResponse holds the response for GETEmpty.
type GETEmptyResponse struct {
	*http.Response
	client *Client
	status200 *edgecases.EmptyStruct
}

func (r *GETEmptyResponse) StatusOk() (*edgecases.EmptyStruct, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(edgecases.EmptyStruct)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETEmpty — Empty struct
func (c *Client) GETEmpty(ctx context.Context) (*GETEmptyResponse, error) {

	u := c.BaseURL + "/empty"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &GETEmptyResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Interface with oneOf
// GET /oneof


// GETOneofResponse holds the response for GETOneof.
type GETOneofResponse struct {
	*http.Response
	client *Client
	status200 *edgecases.WithInterface
}

func (r *GETOneofResponse) StatusOk() (*edgecases.WithInterface, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(edgecases.WithInterface)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETOneof — Interface with oneOf
func (c *Client) GETOneof(ctx context.Context) (*GETOneofResponse, error) {

	u := c.BaseURL + "/oneof"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &GETOneofResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Pointer chain
// GET /pointer-chain


// GETPointerchainResponse holds the response for GETPointerchain.
type GETPointerchainResponse struct {
	*http.Response
	client *Client
	status200 *edgecases.PointerChain
}

func (r *GETPointerchainResponse) StatusOk() (*edgecases.PointerChain, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(edgecases.PointerChain)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETPointerchain — Pointer chain
func (c *Client) GETPointerchain(ctx context.Context) (*GETPointerchainResponse, error) {

	u := c.BaseURL + "/pointer-chain"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &GETPointerchainResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Untyped nil fields
// GET /untyped-nil


// GETUntypednilResponse holds the response for GETUntypednil.
type GETUntypednilResponse struct {
	*http.Response
	client *Client
	status200 *edgecases.WithUntypedNil
}

func (r *GETUntypednilResponse) StatusOk() (*edgecases.WithUntypedNil, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(edgecases.WithUntypedNil)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETUntypednil — Untyped nil fields
func (c *Client) GETUntypednil(ctx context.Context) (*GETUntypednilResponse, error) {

	u := c.BaseURL + "/untyped-nil"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &GETUntypednilResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



