// Code generated by clientgen. DO NOT EDIT.
// Source: 05 Generics Demo v1.0.0

package genericsdemo

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	generics "github.com/arkannsk/nooa/examples/models/05_generics"
)

// HTTPClient is the interface that wraps the Do method.
// It is compatible with *http.Client and useful for testing.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client is the generated HTTP client for 05 Generics Demo.
type Client struct {
	BaseURL     string
	HTTPClient  HTTPClient
	Token       string
	TokenPrefix string
}

// New creates a new Client.
func New(baseURL string, hc HTTPClient) *Client {
	if hc == nil {
		hc = &http.Client{}
	}
	return &Client{
		BaseURL:     strings.TrimRight(baseURL, "/"),
		HTTPClient:  hc,
		TokenPrefix: "Bearer",
	}
}


// Get custom generic struct
// GET /custom-generic


// GETCustomgenericResponse holds the response for GETCustomgeneric.
type GETCustomgenericResponse struct {
	// Status 200 — gen.WithCustomGeneric
	Status200 generics.WithCustomGeneric
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETCustomgeneric — Get custom generic struct
func (c *Client) GETCustomgeneric(ctx context.Context) (*GETCustomgenericResponse, error) {

	u := c.BaseURL + "/custom-generic"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETCustomgenericResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Get generic struct
// GET /generic


// GETGenericResponse holds the response for GETGeneric.
type GETGenericResponse struct {
	// Status 200 — gen.GenericStruct
	Status200 generics.GenericStruct
	// StatusCode is the HTTP status code.
	StatusCode int
	// RawBody is the raw response body.
	RawBody []byte
}

// GETGeneric — Get generic struct
func (c *Client) GETGeneric(ctx context.Context) (*GETGenericResponse, error) {

	u := c.BaseURL + "/generic"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	if c.Token != "" {
		httpReq.Header.Set("Authorization", c.TokenPrefix+" "+c.Token)
	}

	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	result := &GETGenericResponse{
		StatusCode: resp.StatusCode,
		RawBody:    raw,
	}
	if resp.StatusCode == 200 {
		if err := json.Unmarshal(raw, &result.Status200); err != nil {
			return result, fmt.Errorf("unmarshal status 200: %w", err)
		}
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



