// Code generated by elval-gen. DO NOT EDIT.
// Source: nested.go

package nested_structs

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Address) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Street address"
		prop.Example = "123 Main St"

		schema.Properties["street"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "City name"
		prop.Example = "New York"

		schema.Properties["city"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Postal code"
		prop.Example = "12345"

		schema.Properties["zipcode"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Country code (ISO 3166-1 alpha-2)"
		prop.Example = "US"

		schema.Properties["country"] = prop
	}

	return schema
}

func (v *Address) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/03_nested.Address"
}

func (v *UserWithAddress) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "User ID"
		prop.Example = "user_001"

		schema.Properties["id"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "User name"
		prop.Example = "John Doe"

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/github.com/arkannsk/nooa/examples/models/03_nested.Address"

		prop.Description = "Billing address"
		prop.Example = "{\"street\": \"123 Main St\", \"city\": \"New York\", \"zipCode\": \"12345\", \"country\": \"US\"}"

		schema.Properties["billing"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/github.com/arkannsk/nooa/examples/models/03_nested.Address"

		prop.Description = "Shipping address (optional)"
		prop.Example = "{\"street\": \"456 Side St\", \"city\": \"Los Angeles\", \"zipCode\": \"90001\", \"country\": \"US\"}"

		schema.Properties["shipping"] = prop
	}

	return schema
}

func (v *UserWithAddress) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/03_nested.UserWithAddress"
}

func (v *RecursiveNode) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Node value"
		prop.Example = "root"

		schema.Properties["value"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}
		prop.Items.Ref = "#/components/schemas/github.com/arkannsk/nooa/examples/models/03_nested.RecursiveNode"

		prop.Description = "Child nodes"
		prop.Example = "[{\"value\": \"child1\"}]"

		schema.Properties["children"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/github.com/arkannsk/nooa/examples/models/03_nested.RecursiveNode"

		prop.Description = "Parent reference (nullable)"
		prop.Example = "null"

		schema.Properties["parent"] = prop
	}

	return schema
}

func (v *RecursiveNode) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/03_nested.RecursiveNode"
}

func (v *DeepNesting) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		schema.Properties["level1"] = prop
	}

	return schema
}

func (v *DeepNesting) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/03_nested.DeepNesting"
}
