// Code generated by clientgen. DO NOT EDIT.
// Source: 05 Generics Demo v1.0.0

package genericsdemo

import (
	"context"
	"net/http"
	"strings"
	"bytes"
	"fmt"
	"io"
	"sync"
	nooaclient "github.com/arkannsk/nooa/client"
	generics "github.com/arkannsk/nooa/examples/models/05_generics"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// httpc is the internal HTTP client shared by all tag adapters.
type httpc struct {
	BaseURL    string
	HTTPClient HTTPClient
	Codec      map[string]nooaclient.Codec
}

func newHTTPC(baseURL string, hc any) *httpc {
	var httpClient HTTPClient
	switch v := hc.(type) {
	case nil:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		httpClient = &stdHTTPClient{Client: v}
	case HTTPClient:
		httpClient = v
	default:
		httpClient = &stdHTTPClient{Client: &http.Client{}}
	}
	return &httpc{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: httpClient,
	}
}
// V1 is the HTTP client for 05 Generics Demo.
type V1 struct {
	base *httpc
}

// New creates a new V1 client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *V1 {
	return &V1{base: newHTTPC(baseURL, hc)}
}

// Get custom generic struct
// GET /custom-generic
func (c *V1) GETCustomgeneric(ctx context.Context, input *generics.WithCustomGeneric) (*GETCustomgenericResponse, error) {

	path := "/custom-generic"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETCustomgenericResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// Get generic struct
// GET /generic
func (c *V1) GETGeneric(ctx context.Context, input *generics.GenericStruct) (*GETGenericResponse, error) {

	path := "/generic"

	requestURL := c.base.BaseURL + path

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	httpResp, err := c.base.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	return &GETGenericResponse{
		resp:  httpResp,
		codec: c.base.Codec,
	}, nil
}

// GETCustomgenericResponse is the response for the GETCustomgeneric operation.
// Call Close() when done to release the response body.
type GETCustomgenericResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *generics.WithCustomGeneric
}

// Close releases the response body. Always call when done.
func (r *GETCustomgenericResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETCustomgenericResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETCustomgenericResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETCustomgenericResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETCustomgenericResponse) StatusOk() (*generics.WithCustomGeneric, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(generics.WithCustomGeneric)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETGenericResponse is the response for the GETGeneric operation.
// Call Close() when done to release the response body.
type GETGenericResponse struct {
	resp     *http.Response
	codec    map[string]nooaclient.Codec
	bodyOnce sync.Once
	status200 *generics.GenericStruct
}

// Close releases the response body. Always call when done.
func (r *GETGenericResponse) Close() error {
	if r.resp != nil {
		return r.resp.Body.Close()
	}
	return nil
}

// Body returns an io.ReadCloser for the response body.
// After the body is read (e.g. via StatusOk()), a new reader over the cached data is returned.
func (r *GETGenericResponse) Body() io.ReadCloser {
	if r.resp != nil {
		return r.resp.Body
	}
	return nil
}

// readBody reads the response body once and replaces resp.Body with a cached reader
// so subsequent reads (Body(), further Status* calls) can reuse the data.
func (r *GETGenericResponse) readBody() error {
	var err error
	r.bodyOnce.Do(func() {
		data, readErr := io.ReadAll(r.resp.Body)
		if readErr != nil {
			err = readErr
			return
		}
		r.resp.Body = io.NopCloser(bytes.NewReader(data))
	})
	return err
}

// StatusCode returns the HTTP status code of the response.
func (r *GETGenericResponse) StatusCode() int {
	if r.resp != nil {
		return r.resp.StatusCode
	}
	return 0
}

// StatusOk returns the unmarshaled response body for status 200.
func (r *GETGenericResponse) StatusOk() (*generics.GenericStruct, error) {
	if r.status200 != nil {
		return r.status200, nil
	}
	if r.StatusCode() != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode())
	}
	if err := r.readBody(); err != nil {
		return nil, err
	}
	r.status200 = new(generics.GenericStruct)
	if err := nooaclient.UnmarshalResponse(r.resp, r.codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}
