// Code generated by clientgen. DO NOT EDIT.
// Source: 05 Generics Demo v1.0.0

package genericsdemo

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"
	"github.com/arkannsk/nooa/client"
	generics "github.com/arkannsk/nooa/examples/models/05_generics"
)

// HTTPClient is the interface for executing HTTP requests.
// It accepts a context for cancellation and timeouts.
type HTTPClient interface {
	Do(ctx context.Context, req *http.Request) (*http.Response, error)
}

// stdHTTPClient wraps *http.Client to satisfy HTTPClient.
type stdHTTPClient struct {
	*http.Client
}

func (s *stdHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return s.Client.Do(req.WithContext(ctx))
}

// Client is the generated HTTP client for 05 Generics Demo.
type Client struct {
	BaseURL    string
	HTTPClient HTTPClient

	// Codec maps Content-Type to client.Codec for response body decoding.
	// If nil, defaults to JSON decoding for all types.
	Codec map[string]client.Codec
}

// New creates a new Client.
// If hc is nil, a default *http.Client is used.
// If hc is *http.Client, it is automatically wrapped.
func New(baseURL string, hc any) *Client {
	var client HTTPClient
	switch v := hc.(type) {
	case nil:
		client = &stdHTTPClient{Client: &http.Client{}}
	case *http.Client:
		client = &stdHTTPClient{Client: v}
	case HTTPClient:
		client = v
	default:
		client = &stdHTTPClient{Client: &http.Client{}}
	}
	return &Client{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: client,
	}
}


// Get custom generic struct
// GET /custom-generic


// GETCustomgenericResponse holds the response for GETCustomgeneric.
type GETCustomgenericResponse struct {
	*http.Response
	client *Client
	status200 *generics.WithCustomGeneric
}

func (r *GETCustomgenericResponse) StatusOk() (*generics.WithCustomGeneric, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(generics.WithCustomGeneric)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETCustomgeneric — Get custom generic struct
func (c *Client) GETCustomgeneric(ctx context.Context) (*GETCustomgenericResponse, error) {

	u := c.BaseURL + "/custom-generic"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &GETCustomgenericResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



// Get generic struct
// GET /generic


// GETGenericResponse holds the response for GETGeneric.
type GETGenericResponse struct {
	*http.Response
	client *Client
	status200 *generics.GenericStruct
}

func (r *GETGenericResponse) StatusOk() (*generics.GenericStruct, error) {
	if r.StatusCode != 200 {
		return nil, fmt.Errorf("expected status 200, got %d", r.StatusCode)
	}
	if r.status200 != nil {
		return r.status200, nil
	}
	r.status200 = new(generics.GenericStruct)
	if err := client.UnmarshalResponse(r.Response, r.client.Codec, r.status200); err != nil {
		return nil, err
	}
	return r.status200, nil
}

// GETGeneric — Get generic struct
func (c *Client) GETGeneric(ctx context.Context) (*GETGenericResponse, error) {

	u := c.BaseURL + "/generic"

	var body io.Reader

	httpReq, err := http.NewRequestWithContext(ctx, "GET", u, body)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	resp, err := c.HTTPClient.Do(ctx, httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}

	result := &GETGenericResponse{
		Response: resp,
		client:   c,
	}
	if resp.StatusCode >= 400 {
		return result, fmt.Errorf("request failed: status %d", resp.StatusCode)
	}
	return result, nil
}



