// Code generated by elval-gen. DO NOT EDIT.
// Source: uploads.go

package files_streams

import (
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	MixedRequest_CategoriesValidator = func() *validator.SliceValidator[string] {
		v := validator.NewSliceValidator[string]("Categories")
		v.Required()
		v.Min(1)
		return v
	}()
)

func (v *MixedRequest) Validate() error {
	var err *errs.ValidationError
	if err = MixedRequest_CategoriesValidator.Validate(v.Categories); err != nil {
		return err
	}
	return err
}
