// Code generated by elval-gen. DO NOT EDIT.
// Source: uploads.go

package files_streams

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *StandardFileTypes) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 5),
		Required:   make([]string, 0, 5),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "Avatar as *os.File"

		schema.Properties["avatar"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "Payload as io.Reader"

		schema.Properties["payload"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "Thumbnail as io.ReadCloser"

		schema.Properties["thumbnail"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "byte"

		prop.Description = "Data as base64 []byte"

		schema.Properties["data"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "Multipart file"

		schema.Properties["attachment"] = prop
	}

	return schema
}

func (v *StandardFileTypes) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/02_files_stream.StandardFileTypes"
}

func (v *CustomWithAnnotations) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "Custom file reader"

		schema.Properties["avatar"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "Raw stream from custom type"

		schema.Properties["payload"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/*CustomBuffer"

		prop.Description = "Base64 data from custom type"
		prop.Format = "byte"

		schema.Properties["data"] = prop
	}

	return schema
}

func (v *CustomWithAnnotations) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/02_files_stream.CustomWithAnnotations"
}

func (v *MixedRequest) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 5),
		Required:   make([]string, 0, 5),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "Main file"

		schema.Properties["file"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "User ID from form"

		schema.Properties["userid"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Description = "Optional description"

		schema.Properties["description"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		prop.Description = "Tags as comma-separated"

		schema.Properties["tags"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		schema.Required = append(schema.Required, "categories")
		prop.Minimum = oa.Ptr[float64](1)

		prop.Description = "At least one category"

		schema.Properties["categories"] = prop
	}

	return schema
}

func (v *MixedRequest) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/02_files_stream.MixedRequest"
}

func (v *CustomReader) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "byte"

		schema.Properties["data"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["pos"] = prop
	}

	return schema
}

func (v *CustomReader) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/02_files_stream.CustomReader"
}

func (v *CustomStream) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 0),
		Required:   make([]string, 0, 0),
		Ref:        v.GlobalRef(),
	}

	return schema
}

func (v *CustomStream) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/02_files_stream.CustomStream"
}

func (v *CustomBuffer) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 0),
		Required:   make([]string, 0, 0),
		Ref:        v.GlobalRef(),
	}

	return schema
}

func (v *CustomBuffer) GlobalRef() string {
	return "github.com/arkannsk/nooa/examples/models/02_files_stream.CustomBuffer"
}
